"""Emit AWS LZA sample-style configuration from accepted decisions.

This is configuration for an existing accelerator, not a deployment. Nothing here
calls AWS, holds credentials, or applies anything. Emission is fail-closed: an
open gap or an unresolved conflict blocks the bundle.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from .analysis import raw_values, semantic_conflicts
from .catalog import coerce
from .contract import CONFIG_FILES, LZA_COMMIT, LZA_VERSION, validate_configs
from .models import Decision, Fact, Review

_HEADER = (
    "# Generated by iac-llm-wrapper from accepted architecture decisions.\n"
    "# Source document sha256: {sha256}\n"
    "# Configuration for the AWS Landing Zone Accelerator. Not a deployment.\n"
)
_WORKLOAD_OU = "Workloads"


class EmitBlocked(Exception):
    """Decisions are not ready to emit. Distinct from a write failure."""


@dataclass
class Resolution:
    values: dict[str, Any]
    trace: list[dict[str, str]] = field(default_factory=list)


def resolve(
    catalog: dict[str, Decision],
    review: Review,
    facts: list[Fact],
    allow_defaults: bool = False,
) -> Resolution:
    if review.conflicts:
        codes = ", ".join(sorted({conflict.code for conflict in review.conflicts}))
        raise EmitBlocked(f"unresolved conflicts block emission: {codes}")

    stated = raw_values(facts)
    evidence = {fact.decision_key: f"{fact.section}:{fact.line}" for fact in facts}
    resolution = Resolution(values={})
    missing: list[str] = []

    for key in review.applicable:
        decision = catalog[key]
        raw = stated.get(key)
        origin = "document"
        if raw is None:
            if not allow_defaults or decision.default is None:
                missing.append(f"{key} ({decision.question})")
                continue
            raw = decision.default
            origin = "default"
        try:
            resolution.values[key] = coerce(decision, raw)
        except ValueError as exc:
            raise EmitBlocked(str(exc)) from exc
        resolution.trace.append(
            {
                "decision": key,
                "value": raw,
                "origin": origin,
                "evidence": evidence.get(key, "catalog default"),
            }
        )

    if missing:
        listed = "\n  - ".join(missing)
        raise EmitBlocked(f"unanswered applicable decisions block emission:\n  - {listed}")
    # Defaults can introduce conflicts that did not exist among the stated facts.
    resolved_facts = facts + [
        Fact(
            decision_key=entry["decision"],
            value=entry["value"],
            section="catalog default",
            line=0,
            origin="default",
        )
        for entry in resolution.trace
        if entry["origin"] == "default"
    ]
    conflicts = semantic_conflicts(catalog, resolved_facts)
    if conflicts:
        codes = ", ".join(sorted({conflict.code for conflict in conflicts}))
        raise EmitBlocked(f"resolved decisions block emission: {codes}")
    return resolution


def emit_bundle(resolution: Resolution, review: Review, out_dir: Path) -> list[Path]:
    values = resolution.values
    documents = {
        "organization-config.yaml": _organization_config(values),
        "accounts-config.yaml": _accounts_config(values),
        "global-config.yaml": _global_config(values),
        "iam-config.yaml": _iam_config(values),
        "network-config.yaml": _network_config(values),
        "security-config.yaml": _security_config(values),
    }
    errors = validate_configs(documents)
    if errors:
        raise EmitBlocked(f"LZA {LZA_VERSION} schema validation failed:\n" + "\n".join(errors))
    documents.update(
        {
            "decision-trace.yaml": {
                "sourceDocument": review.document,
                "sourceSha256": review.sha256,
                "decisions": resolution.trace,
            },
            "handoff.yaml": _handoff(values),
        }
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, data in documents.items():
        written.append(_write_yaml(out_dir / name, data, review.sha256))
    return written


def _write_yaml(path: Path, data: dict[str, Any], sha256: str) -> Path:
    yaml = YAML(typ="safe")
    yaml.default_flow_style = False
    with path.open("w", encoding="utf-8") as handle:
        if path.name in CONFIG_FILES:
            handle.write(
                "# yaml-language-server: $schema=https://raw.githubusercontent.com/"
                f"awslabs/landing-zone-accelerator-on-aws/{LZA_COMMIT}/"
                "source/packages/@aws-accelerator/config/lib/schemas/"
                f"{path.stem}.json\n"
            )
        handle.write(_HEADER.format(sha256=sha256))
        yaml.dump(data, handle)
    return path


def _handoff(values: dict[str, Any]) -> dict[str, Any]:
    return {
        "target": {"name": "AWS Landing Zone Accelerator", "version": LZA_VERSION},
        "status": "requires-owner-validation",
        "configurationFiles": list(CONFIG_FILES),
        "owner": values["application_owner"],
        "layers": {
            "network": {
                "topology": values["topology"],
                "ownerAction": "Complete routes, subnets, attachments, DNS and inspection.",
            },
            "identity": {
                "policyMappings": values["identity_center_policy_mappings"],
                "ownerAction": "Verify policies, identity-provider groups and assignments.",
            },
            "data": {
                "classification": values["data_classification"],
                "approvedRegions": values["data_regions"],
                "recoveryObjectives": values["recovery_objectives"],
                "ownerAction": "Configure keys, retention and backups; prove restore objectives.",
            },
            "application": {
                "ownerAction": "Integrate runtime and dependencies in the application pipeline.",
            },
        },
        "validation": {
            "schema": f"passed: LZA {LZA_VERSION}",
            "ownerPipeline": "Run LZA validation and review synthesized changes before deployment.",
            "scope": "Schema checks do not establish completeness, compliance or deployability.",
        },
    }


def _emails(values: dict[str, Any]) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for entry in values.get("account_emails") or []:
        account, _, email = entry.partition("=")
        mapping[account.strip()] = email.strip()
    return mapping


def _email_for(values: dict[str, Any], account: str) -> str:
    email = _emails(values).get(account)
    if not email:
        raise EmitBlocked(
            f"account '{account}' has no approved root email in account_emails; "
            "account emails are owner input and are never generated"
        )
    return email


def _account(values: dict[str, Any], name: str, ou: str, description: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "email": _email_for(values, name),
        "organizationalUnit": ou,
    }


def _network_host_account(values: dict[str, Any]) -> str:
    if values.get("topology") == "hub-spoke":
        return str(values["network_account"])
    workloads = values.get("workload_accounts") or []
    return str(workloads[0]) if workloads else "Management"


def _organization_config(values: dict[str, Any]) -> dict[str, Any]:
    return {
        "enable": True,
        "organizationalUnits": [{"name": name} for name in values["organizational_units"]],
        "serviceControlPolicies": [],
        "taggingPolicies": [],
        "backupPolicies": [],
    }


def _accounts_config(values: dict[str, Any]) -> dict[str, Any]:
    mandatory = [
        _account(values, "Management", "Root", "Organization management account"),
        _account(values, values["log_archive_account"], "Security", "Central log archive"),
        _account(values, values["audit_account"], "Security", "Security audit account"),
        _account(
            values,
            values["security_tooling_account"],
            "Security",
            "Delegated security tooling administration",
        ),
    ]
    if values.get("network_account"):
        mandatory.append(
            _account(values, values["network_account"], "Infrastructure", "Shared networking")
        )
    return {
        "mandatoryAccounts": mandatory,
        "workloadAccounts": [
            _account(values, name, _WORKLOAD_OU, "Workload account")
            for name in values.get("workload_accounts") or []
        ],
    }


def _global_config(values: dict[str, Any]) -> dict[str, Any]:
    centralized = bool(values["centralized_logging"])
    return {
        "homeRegion": values["home_region"],
        "enabledRegions": values["enabled_regions"],
        "managementAccountAccessRole": "AWSControlTowerExecution"
        if values["org_mode"] == "control-tower"
        else "OrganizationAccountAccessRole",
        "terminationProtection": True,
        "cloudwatchLogRetentionInDays": 2555,
        "controlTower": {"enable": values["org_mode"] == "control-tower"},
        "cdkOptions": {"centralizeBuckets": True, "useManagementAccessRole": True},
        "logging": {
            "account": values["log_archive_account"],
            "centralizedLoggingRegion": values["home_region"],
            "cloudtrail": {"enable": centralized, "organizationTrail": centralized},
            "sessionManager": {
                "sendToCloudWatchLogs": centralized,
                "sendToS3": centralized,
            },
        },
        "tags": [{"key": "Organization", "value": values["organization_name"]}],
    }


def _iam_config(values: dict[str, Any]) -> dict[str, Any]:
    policies: dict[str, list[str]] = {}
    for entry in values["identity_center_policy_mappings"]:
        name, _, policy = (part.strip() for part in entry.partition("="))
        policies.setdefault(name, []).append(policy)
    assignments: list[dict[str, Any]] = []
    for entry in values.get("identity_center_assignments") or []:
        principal, permission_set, account = (part.strip() for part in entry.split(":"))
        assignments.append(
            {
                "name": f"{principal}-{permission_set}-{account}",
                "permissionSetName": permission_set,
                "principals": [{"type": "GROUP", "name": principal}],
                "deploymentTargets": {"accounts": [account]},
            }
        )
    return {
        "homeRegion": values["home_region"],
        "identityCenter": {
            "name": "identityCenter",
            "delegatedAdminAccount": values["identity_center_delegated_admin_account"],
            "identityCenterPermissionSets": [
                {"name": name, "policies": {"awsManaged": policies[name]}, "sessionDuration": 60}
                for name in values.get("identity_center_permission_sets") or []
            ],
            "identityCenterAssignments": assignments,
        },
    }


def _network_config(values: dict[str, Any]) -> dict[str, Any]:
    host = _network_host_account(values)
    config: dict[str, Any] = {
        "homeRegion": values["home_region"],
        "defaultVpc": {"delete": False, "excludeAccounts": []},
        "endpointPolicies": [],
        "transitGateways": [],
        "vpcs": [
            {
                "name": "Core",
                "account": host,
                "region": values["home_region"],
                "cidrs": [values["network_cidr"]],
                "enableDnsHostnames": True,
                "enableDnsSupport": True,
                "instanceTenancy": "default",
                "routeTables": [],
                "subnets": [],
                "natGateways": [],
                "transitGatewayAttachments": [],
                "tags": [],
            }
        ],
        "centralNetworkServices": {"delegatedAdminAccount": host},
    }
    if values.get("topology") == "hub-spoke":
        config["transitGateways"] = [
            {
                "name": "Core",
                "account": host,
                "region": values["home_region"],
                "asn": 64512,
                "dnsSupport": "enable",
                "vpnEcmpSupport": "enable",
                "defaultRouteTableAssociation": "disable",
                "defaultRouteTablePropagation": "disable",
                "autoAcceptSharingAttachments": "disable",
                "routeTables": [],
                "shareTargets": {
                    "organizationalUnits": [
                        name for name in values["organizational_units"] if name != "Security"
                    ]
                },
                "tags": [],
            }
        ]
    return config


def _security_config(values: dict[str, Any]) -> dict[str, Any]:
    strict = values["compliance_overlay"] != "none"
    return {
        "homeRegion": values["home_region"],
        "accessAnalyzer": {"enable": True},
        "iamPasswordPolicy": {
            "minimumPasswordLength": 14,
            "requireUppercaseCharacters": True,
            "requireLowercaseCharacters": True,
            "requireSymbols": True,
            "requireNumbers": True,
            "passwordReusePrevention": 24,
            "maxPasswordAge": 90,
            "hardExpiry": False,
            "allowUsersToChangePassword": True,
        },
        "awsConfig": {"enableConfigurationRecorder": True},
        "cloudWatch": {"metricSets": [], "alarmSets": []},
        "centralSecurityServices": {
            "delegatedAdminAccount": values["security_tooling_account"],
            "ssmAutomation": {"documentSets": []},
            "ebsDefaultVolumeEncryption": {"enable": True, "excludeRegions": []},
            "s3PublicAccessBlock": {"enable": True, "excludeAccounts": []},
            "scpRevertChangesConfig": {"enable": True},
            "macie": {"enable": strict, "excludeRegions": []},
            "guardduty": {
                "enable": bool(values["guardduty_enabled"]),
                "excludeRegions": [],
                "s3Protection": {"enable": bool(values["guardduty_enabled"])},
                "exportConfiguration": {
                    "enable": False,
                    "destinationType": "S3",
                    "exportFrequency": "SIX_HOURS",
                },
            },
            "securityHub": {
                "enable": bool(values["security_hub_enabled"]),
                "regionAggregation": True,
                "excludeRegions": [],
                "standards": _standards(values),
            },
        },
    }


def _standards(values: dict[str, Any]) -> list[dict[str, Any]]:
    if not values["security_hub_enabled"]:
        return []
    standards = [{"name": "AWS Foundational Security Best Practices v1.0.0", "enable": True}]
    if values["compliance_overlay"] != "none":
        standards.append({"name": "CIS AWS Foundations Benchmark v1.4.0", "enable": True})
    return standards
