"""Export validated LZA configuration and a sourced decision trace."""

from __future__ import annotations

import hashlib
import io
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML, YAMLError

from .analysis import first_facts, integration_context, semantic_conflicts
from .catalog import coerce
from .contract import CONFIG_FILES, LZA_COMMIT, LZA_VERSION, validate_configs
from .models import Assessment, Decision, Review
from .organisation import assess
from .output import EmitBlocked, write_bundle

_HEADER = (
    "# Generated by iac-llm-wrapper from accepted architecture decisions.\n"
    "# Source document sha256: {sha256}\n"
    "# Configuration for the AWS Landing Zone Accelerator. Not a deployment.\n"
)


@dataclass
class Resolution:
    values: dict[str, Any]
    trace: list[dict[str, str]] = field(default_factory=list)
    assessments: list[Assessment] = field(default_factory=list)


def resolve(
    catalog: dict[str, Decision],
    review: Review,
    *,
    allow_defaults: bool = False,
) -> Resolution:
    if review.conflicts:
        codes = ", ".join(sorted({conflict.code for conflict in review.conflicts}))
        raise EmitBlocked(f"unresolved conflicts block emission: {codes}")

    stated = first_facts(review.facts)
    resolution = Resolution(values={})
    missing: list[str] = []

    for key in review.applicable:
        decision = catalog[key]
        fact = stated.get(key)
        raw = fact.value if fact else None
        origin = "document"
        if raw is None:
            if not allow_defaults or decision.default is None:
                missing.append(f"{key} ({decision.question})")
                continue
            raw = decision.default
            origin = "default"
        try:
            resolution.values[key] = coerce(decision, raw)
        except ValueError as exc:
            raise EmitBlocked(str(exc)) from exc
        resolution.trace.append(
            {
                "decision": key,
                "value": raw,
                "origin": origin,
                "evidence": f"{fact.section}:{fact.line}" if fact else "catalog default",
            }
        )

    if missing:
        listed = "\n  - ".join(missing)
        raise EmitBlocked(f"unanswered applicable decisions block emission:\n  - {listed}")
    # Defaults can introduce conflicts that did not exist among the stated facts.
    conflicts = semantic_conflicts(resolution.values)
    if conflicts:
        codes = ", ".join(sorted({conflict.code for conflict in conflicts}))
        raise EmitBlocked(f"resolved decisions block emission: {codes}")
    resolution.assessments = assess(review.organisation, resolution.values)
    if any(a.status in {"conflict", "not-assessed"} for a in resolution.assessments):
        raise EmitBlocked("organisation policy assessment blocks resolved values")
    return resolution


def emit_bundle(
    resolution: Resolution,
    review: Review,
    out_dir: Path,
    network_config: Path | None = None,
) -> list[Path]:
    values = resolution.values
    context_keys = {d.key for d in review.organisation.questions} if review.organisation else set()
    trace = [
        {**entry, "output": "context-only; configured by the consuming enterprise team"}
        if entry["decision"] in context_keys
        else entry
        for entry in resolution.trace
    ]
    sources = {Path(review.document).resolve()}
    if review.organisation:
        sources.update(Path(r.path).resolve() for r in review.organisation.references)
    if any(
        (out_dir / name).resolve() in sources
        for name in (*CONFIG_FILES, "decision-trace.yaml", "handoff.yaml")
    ):
        raise EmitBlocked("keep source documents and references separate from generated files")
    documents = {
        "organization-config.yaml": _organization_config(values),
        "accounts-config.yaml": _accounts_config(values),
        "global-config.yaml": _global_config(values),
        "iam-config.yaml": _iam_config(values),
        "network-config.yaml": _network_config(values),
        "security-config.yaml": _security_config(values),
    }
    network_source = None
    if network_config is not None:
        source = network_config.resolve()
        output_names = (*CONFIG_FILES, "decision-trace.yaml", "handoff.yaml")
        if source.is_relative_to(out_dir.resolve()) or any(
            (out_dir / name).resolve() == source for name in output_names
        ):
            raise EmitBlocked("keep the owner network file separate from the output bundle")
        documents["network-config.yaml"], network_source = _read_network(network_config)
    errors = validate_configs(documents)
    if errors:
        raise EmitBlocked(f"LZA {LZA_VERSION} schema validation failed:\n" + "\n".join(errors))
    if network_source is not None:
        _check_network_intent(documents["network-config.yaml"], values)
    context = integration_context(values)
    context["validation"]["schema"] = f"passed: LZA {LZA_VERSION}"
    if network_source is not None:
        context["layers"]["network"]["source"] = network_source
        context["layers"]["network"]["ownerAction"] = (
            "Validate routing and connectivity in the owner pipeline."
        )
    documents["decision-trace.yaml"] = {
        "sourceDocument": review.document,
        "sourceSha256": review.sha256,
        "decisions": trace,
        "integrationContext": context,
        "organisation": review.organisation.model_dump(
            exclude={"references": {"__all__": {"content"}}}
        )
        if review.organisation
        else None,
        "policyAssessments": [a.model_dump() for a in resolution.assessments],
    }
    if (out_dir / "handoff.yaml").exists() or (out_dir / "handoff.yaml").is_symlink():
        raise EmitBlocked("output contains a legacy handoff.yaml; use a fresh output directory")
    return write_bundle(
        out_dir, {name: _render_yaml(name, data, review.sha256) for name, data in documents.items()}
    )


def _read_network(path: Path) -> tuple[dict[str, Any], dict[str, str]]:
    try:
        content = path.read_bytes()
        network = YAML(typ="safe").load(content.decode("utf-8"))
    except (OSError, UnicodeError, YAMLError) as exc:
        raise EmitBlocked(f"{path}: cannot read owner network configuration: {exc}") from exc
    if not isinstance(network, dict):
        raise EmitBlocked(f"{path}: owner network configuration must be a YAML mapping")
    return network, {
        "origin": "owner-file",
        "path": str(path),
        "sha256": hashlib.sha256(content).hexdigest(),
    }


def _check_network_intent(network: dict[str, Any], values: dict[str, Any]) -> None:
    """Keep the integration aligned with the packet; detailed routing remains owner work."""
    host = _network_host_account(values)
    home = values["home_region"]
    if network.get("homeRegion") != home:
        raise EmitBlocked("owner network homeRegion differs from the packet home_region")
    vpcs = network.get("vpcs", [])
    if not any(
        vpc["account"] == host
        and vpc["region"] == home
        and values["network_cidr"] in vpc.get("cidrs", [])
        for vpc in vpcs
    ):
        raise EmitBlocked(
            "owner network needs a VPC matching the packet's host, region and network_cidr"
        )
    gateways = network.get("transitGateways", [])
    if values["topology"] == "hub-spoke":
        if not any(tgw["account"] == host and tgw["region"] == home for tgw in gateways):
            raise EmitBlocked(
                "owner hub-spoke network needs a transit gateway in the packet's host and region"
            )
    elif gateways:
        raise EmitBlocked("owner network has transit gateways but the packet selects single-vpc")


def _render_yaml(name: str, data: dict[str, Any], sha256: str) -> str:
    yaml = YAML(typ="safe")
    yaml.default_flow_style = False
    handle = io.StringIO()
    if name in CONFIG_FILES:
        handle.write(
            "# yaml-language-server: $schema=https://raw.githubusercontent.com/"
            f"awslabs/landing-zone-accelerator-on-aws/{LZA_COMMIT}/"
            "source/packages/@aws-accelerator/config/lib/schemas/"
            f"{Path(name).stem}.json\n"
        )
    handle.write(_HEADER.format(sha256=sha256))
    yaml.dump(data, handle)
    return handle.getvalue()


def _account(emails: dict[str, str], name: str, ou: str, description: str) -> dict[str, str]:
    email = emails.get(name)
    if not email:
        raise EmitBlocked(
            f"account '{name}' has no approved root email in account_emails; "
            "account emails are owner input and are never generated"
        )
    return {
        "name": name,
        "description": description,
        "email": email,
        "organizationalUnit": ou,
    }


def _network_host_account(values: dict[str, Any]) -> str:
    if values.get("topology") == "hub-spoke":
        return str(values["network_account"])
    workloads = values.get("workload_accounts") or []
    return str(workloads[0]) if workloads else "Management"


def _organization_config(values: dict[str, Any]) -> dict[str, Any]:
    return {
        "enable": True,
        "organizationalUnits": [{"name": name} for name in values["organizational_units"]],
        "serviceControlPolicies": [],
        "taggingPolicies": [],
        "backupPolicies": [],
    }


def _accounts_config(values: dict[str, Any]) -> dict[str, Any]:
    emails = {}
    for entry in values["account_emails"]:
        account, _, email = entry.partition("=")
        emails[account.strip()] = email.strip()
    mandatory = [
        _account(emails, "Management", "Root", "Organization management account"),
        _account(emails, values["log_archive_account"], "Security", "Central log archive"),
        _account(emails, values["audit_account"], "Security", "Security audit account"),
        _account(
            emails,
            values["security_tooling_account"],
            "Security",
            "Delegated security tooling administration",
        ),
    ]
    if values.get("network_account"):
        mandatory.append(
            _account(emails, values["network_account"], "Infrastructure", "Shared networking")
        )
    return {
        "mandatoryAccounts": mandatory,
        "workloadAccounts": [
            _account(emails, name, "Workloads", "Workload account")
            for name in values.get("workload_accounts") or []
        ],
    }


def _global_config(values: dict[str, Any]) -> dict[str, Any]:
    centralized = values["centralized_logging"]
    return {
        "homeRegion": values["home_region"],
        "enabledRegions": values["enabled_regions"],
        "managementAccountAccessRole": "AWSControlTowerExecution"
        if values["org_mode"] == "control-tower"
        else "OrganizationAccountAccessRole",
        "terminationProtection": True,
        "cloudwatchLogRetentionInDays": 2555,
        "controlTower": {"enable": values["org_mode"] == "control-tower"},
        "cdkOptions": {"centralizeBuckets": True, "useManagementAccessRole": True},
        "logging": {
            "account": values["log_archive_account"],
            "centralizedLoggingRegion": values["home_region"],
            "cloudtrail": {"enable": centralized, "organizationTrail": centralized},
            "sessionManager": {
                "sendToCloudWatchLogs": centralized,
                "sendToS3": centralized,
            },
        },
        "tags": [{"key": "Organization", "value": values["organization_name"]}],
    }


def _iam_config(values: dict[str, Any]) -> dict[str, Any]:
    policies: dict[str, list[str]] = {}
    for entry in values["identity_center_policy_mappings"]:
        name, _, policy = (part.strip() for part in entry.partition("="))
        policies.setdefault(name, []).append(policy)
    assignments: list[dict[str, Any]] = []
    for entry in values.get("identity_center_assignments") or []:
        principal, permission_set, account = (part.strip() for part in entry.split(":"))
        assignments.append(
            {
                "name": f"{principal}-{permission_set}-{account}",
                "permissionSetName": permission_set,
                "principals": [{"type": "GROUP", "name": principal}],
                "deploymentTargets": {"accounts": [account]},
            }
        )
    return {
        "homeRegion": values["home_region"],
        "identityCenter": {
            "name": "identityCenter",
            "delegatedAdminAccount": values["identity_center_delegated_admin_account"],
            "identityCenterPermissionSets": [
                {"name": name, "policies": {"awsManaged": policies[name]}, "sessionDuration": 60}
                for name in values.get("identity_center_permission_sets") or []
            ],
            "identityCenterAssignments": assignments,
        },
    }


def _network_config(values: dict[str, Any]) -> dict[str, Any]:
    host = _network_host_account(values)
    config: dict[str, Any] = {
        "homeRegion": values["home_region"],
        "defaultVpc": {"delete": False, "excludeAccounts": []},
        "endpointPolicies": [],
        "transitGateways": [],
        "vpcs": [
            {
                "name": "Core",
                "account": host,
                "region": values["home_region"],
                "cidrs": [values["network_cidr"]],
                "enableDnsHostnames": True,
                "enableDnsSupport": True,
                "instanceTenancy": "default",
                "routeTables": [],
                "subnets": [],
                "natGateways": [],
                "transitGatewayAttachments": [],
                "tags": [],
            }
        ],
        "centralNetworkServices": {"delegatedAdminAccount": host},
    }
    if values.get("topology") == "hub-spoke":
        config["transitGateways"] = [
            {
                "name": "Core",
                "account": host,
                "region": values["home_region"],
                "asn": 64512,
                "dnsSupport": "enable",
                "vpnEcmpSupport": "enable",
                "defaultRouteTableAssociation": "disable",
                "defaultRouteTablePropagation": "disable",
                "autoAcceptSharingAttachments": "disable",
                "routeTables": [],
                "shareTargets": {
                    "organizationalUnits": [
                        name for name in values["organizational_units"] if name != "Security"
                    ]
                },
                "tags": [],
            }
        ]
    return config


def _security_config(values: dict[str, Any]) -> dict[str, Any]:
    strict = values["compliance_overlay"] != "none"
    standards = []
    if values["security_hub_enabled"]:
        standards.append(
            {"name": "AWS Foundational Security Best Practices v1.0.0", "enable": True}
        )
        if strict:
            standards.append({"name": "CIS AWS Foundations Benchmark v1.4.0", "enable": True})
    return {
        "homeRegion": values["home_region"],
        "accessAnalyzer": {"enable": True},
        "iamPasswordPolicy": {
            "minimumPasswordLength": 14,
            "requireUppercaseCharacters": True,
            "requireLowercaseCharacters": True,
            "requireSymbols": True,
            "requireNumbers": True,
            "passwordReusePrevention": 24,
            "maxPasswordAge": 90,
            "hardExpiry": False,
            "allowUsersToChangePassword": True,
        },
        "awsConfig": {"enableConfigurationRecorder": True},
        "cloudWatch": {"metricSets": [], "alarmSets": []},
        "centralSecurityServices": {
            "delegatedAdminAccount": values["security_tooling_account"],
            "ssmAutomation": {"documentSets": []},
            "ebsDefaultVolumeEncryption": {"enable": True, "excludeRegions": []},
            "s3PublicAccessBlock": {"enable": True, "excludeAccounts": []},
            "scpRevertChangesConfig": {"enable": True},
            "macie": {"enable": strict, "excludeRegions": []},
            "guardduty": {
                "enable": values["guardduty_enabled"],
                "excludeRegions": [],
                "s3Protection": {"enable": values["guardduty_enabled"]},
                "exportConfiguration": {
                    "enable": False,
                    "destinationType": "S3",
                    "exportFrequency": "SIX_HOURS",
                },
            },
            "securityHub": {
                "enable": values["security_hub_enabled"],
                "regionAggregation": True,
                "excludeRegions": [],
                "standards": standards,
            },
        },
    }
