"""Battle-test confidence summary helpers."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import ruamel.yaml

from .yaml_utils import write_yaml_artifact

_BATTLE_SUMMARY_HEADER = (
    "# yaml-language-server: $schema=none\n"
    "# Generated by intent-engine - battle-test confidence summary.\n"
)


@dataclass(frozen=True)
class BattleCaseInput:
    """Fixture expectations needed to score a battle-test run."""

    name: str
    input_path: Path
    pattern: str
    expected_compile: str
    expected_artifacts: tuple[str, ...]
    expected_violations: tuple[str, ...]


@dataclass(frozen=True)
class BattleCompileResult:
    """Compile process result fields needed by battle scoring."""

    returncode: int
    stdout: str
    stderr: str


def load_optional_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    yaml = ruamel.yaml.YAML(typ="safe")
    data = yaml.load(path.read_text())
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected mapping")
    return data


def summarize_battle_artifacts(output_dir: Path) -> dict[str, Any]:
    benchmark = load_optional_yaml(output_dir / "model-benchmark.yaml")
    validation = load_optional_yaml(output_dir / "contract-validation.yaml")
    run = benchmark.get("run", {}) if isinstance(benchmark.get("run"), dict) else {}
    latency = benchmark.get("latency", {}) if isinstance(benchmark.get("latency"), dict) else {}
    tokens = benchmark.get("tokens", {}) if isinstance(benchmark.get("tokens"), dict) else {}
    quality = benchmark.get("quality", {}) if isinstance(benchmark.get("quality"), dict) else {}
    readiness = (
        benchmark.get("readiness", {}) if isinstance(benchmark.get("readiness"), dict) else {}
    )
    validation_summary = (
        validation.get("summary", {}) if isinstance(validation.get("summary"), dict) else {}
    )
    return {
        "mode": run.get("mode", "unknown"),
        "provider": run.get("provider", "unknown"),
        "model": run.get("model", "unknown"),
        "readiness": readiness.get("status", "unknown"),
        "latencyMs": latency.get("totalMs", 0),
        "tokens": tokens.get("totalTokens", 0),
        "acceptedDecisions": quality.get("acceptedDecisionCount", 0),
        "parseErrors": quality.get("parseErrorCount", 0),
        "contractStatus": validation_summary.get("status", "unknown"),
    }


def write_battle_summary(path: Path, data: dict[str, Any]) -> None:
    write_yaml_artifact(path, data, _BATTLE_SUMMARY_HEADER)


def build_battle_summary(
    *,
    case: BattleCaseInput,
    output_dir: Path,
    command: list[str],
    use_llm: bool,
    compile_result: BattleCompileResult,
    repo_root: Path,
    git_commit: str,
) -> dict[str, Any]:
    from .patterns import GLOBAL_REGISTRY

    pattern = GLOBAL_REGISTRY.get(case.pattern)
    trace = load_optional_yaml(output_dir / "llm-trace-summary.yaml")
    validation = load_optional_yaml(output_dir / "contract-validation.yaml")
    handoff = load_optional_yaml(output_dir / "handoff-plan.yaml")
    decision_report = load_optional_yaml(output_dir / "decision-report.yaml")

    summary = summarize_battle_artifacts(output_dir)
    findings: list[dict[str, str]] = []
    compile_succeeded = compile_result.returncode == 0
    expected_pass = case.expected_compile == "pass"
    combined_output = f"{compile_result.stdout}\n{compile_result.stderr}"

    if compile_succeeded != expected_pass:
        findings.append(
            _finding(
                "fail",
                "safety",
                f"Compile result mismatch: expected {case.expected_compile}, got "
                f"{'pass' if compile_succeeded else 'fail'}.",
            )
        )
    for expected_violation in case.expected_violations:
        if expected_violation not in combined_output and expected_violation not in str(
            decision_report
        ):
            findings.append(
                _finding(
                    "fail",
                    "safety",
                    f"Expected violation not surfaced: {expected_violation}.",
                )
            )

    accepted = trace.get("acceptedDecisions", {})
    raw_llm = trace.get("rawLlmDecisions", {})
    raw_llm_signals = trace.get("rawLlmSignalDecisions", {})
    applied = trace.get("appliedDecisions", {})
    gaps = trace.get("gaps", {})
    contradictions = trace.get("contradictions", {})
    if not isinstance(accepted, dict) or not accepted:
        findings.append(_finding("fail", "extraction", "No accepted decisions captured."))
    if isinstance(accepted, dict):
        required_decisions = {
            key for contract in pattern.contracts for key in contract.required_decisions
        }
        missing = sorted(key for key in required_decisions if key not in accepted)
        if missing and expected_pass:
            findings.append(
                _finding(
                    "fail",
                    "extraction",
                    f"Required target decisions missing: {', '.join(missing)}.",
                )
            )
    if isinstance(raw_llm, dict):
        invented = sorted(set(raw_llm) - set(accepted)) if isinstance(accepted, dict) else []
        if invented:
            findings.append(
                _finding(
                    "improvement",
                    "extraction",
                    f"Raw LLM decisions were not accepted by graph: {', '.join(invented)}.",
                )
            )
    if use_llm and isinstance(accepted, dict) and isinstance(raw_llm, dict):
        raw_llm_keys = set(raw_llm)
        if isinstance(raw_llm_signals, dict):
            raw_llm_keys.update(raw_llm_signals)
        missing_from_raw_llm = sorted(set(accepted) - raw_llm_keys)
        if missing_from_raw_llm:
            findings.append(
                _finding(
                    "expected-weakness",
                    "model",
                    f"Raw LLM missed accepted decisions: {', '.join(missing_from_raw_llm)}.",
                )
            )
    if isinstance(applied, dict):
        markdown_applied = applied.get("markdown", [])
        llm_applied = applied.get("llm", [])
        if markdown_applied and not llm_applied and use_llm:
            findings.append(
                _finding(
                    "expected-weakness",
                    "model",
                    "Structured Markdown carried the handoff; LLM added no accepted decisions.",
                )
            )
    if isinstance(gaps, dict):
        raw_gaps = gaps.get("raw", [])
        blocking_gaps = gaps.get("blocking", [])
        if (
            isinstance(raw_gaps, list)
            and isinstance(blocking_gaps, list)
            and len(blocking_gaps) > len(raw_gaps)
        ):
            findings.append(_finding("fail", "extraction", "Blocking gaps exceed raw LLM gaps."))
    if isinstance(contradictions, dict):
        blocking_contradictions = contradictions.get("blocking", [])
        if blocking_contradictions and expected_pass:
            findings.append(
                _finding(
                    "fail",
                    "safety",
                    "Blocking contradictions surfaced in an expected-pass battle.",
                )
            )

    artifact_status = _artifact_status(output_dir, case.expected_artifacts)
    missing_artifacts = [item["name"] for item in artifact_status if item["status"] != "present"]
    if missing_artifacts and expected_pass:
        findings.append(
            _finding(
                "fail",
                "handoff",
                f"Expected artifacts missing: {', '.join(missing_artifacts)}.",
            )
        )
    validation_summary = validation.get("summary", {})
    if expected_pass and (
        not isinstance(validation_summary, dict) or validation_summary.get("status") != "pass"
    ):
        findings.append(_finding("fail", "handoff", "Contract validation did not pass."))
    allowed_next_action = handoff.get("allowedNextAction")
    if expected_pass and not allowed_next_action:
        findings.append(_finding("fail", "handoff", "handoff-plan.yaml has no allowedNextAction."))
    review_path = output_dir / "handoff-review.html"
    if expected_pass and not review_path.exists():
        findings.append(_finding("fail", "handoff", "Review page was not generated."))
    elif review_path.exists():
        review_text = review_path.read_text()
        for marker in ("Readiness", "Contract Validation", "Model Benchmark"):
            if marker not in review_text:
                findings.append(
                    _finding("fail", "handoff", f"Review page missing section: {marker}.")
                )

    for forbidden in pattern.forbidden_artifacts:
        if (output_dir / forbidden).exists():
            findings.append(
                _finding(
                    "fail",
                    "safety",
                    f"Unexpected forbidden artifact emitted: {forbidden}.",
                )
            )
    if use_llm and not (output_dir / "raw-evidence.yaml").exists():
        findings.append(_finding("fail", "safety", "Raw LLM evidence was not preserved."))

    if use_llm:
        if summary["latencyMs"] in (0, "0", None):
            findings.append(_finding("fail", "model", "Latency was not captured."))
        if summary["parseErrors"]:
            findings.append(_finding("fail", "model", "LLM parse errors were captured."))
        if summary["tokens"] in (0, "0", None):
            findings.append(
                _finding(
                    "expected-weakness",
                    "model",
                    "Provider did not report token usage.",
                )
            )
    if not (output_dir / "model-benchmark.yaml").exists():
        findings.append(_finding("fail", "model", "model-benchmark.yaml missing."))

    confidence = {
        "extraction": _confidence_status(findings, "extraction"),
        "handoff": _confidence_status(findings, "handoff"),
        "safety": _confidence_status(findings, "safety"),
        "model": _confidence_status(findings, "model"),
        "regression": "pass" if not any(item["type"] == "fail" for item in findings) else "fail",
    }
    verdict = "fail" if confidence["regression"] == "fail" else "pass"
    return {
        "schemaVersion": "intent-engine/battle-summary/v1",
        "verdict": verdict,
        "meaning": "confidence increased" if verdict == "pass" else "bug or weakness found",
        "fixture": case.name,
        "pattern": case.pattern,
        "input": str(case.input_path.relative_to(repo_root)),
        "expectedCompile": case.expected_compile,
        "actualCompile": "pass" if compile_succeeded else "fail",
        "generatedAt": datetime.now(UTC).isoformat(),
        "gitCommit": git_commit,
        "command": " ".join(command),
        "output": {
            "directory": str(output_dir),
            "reviewPage": str(output_dir / "handoff-review.html"),
            "battleSummary": str(output_dir / "battle-summary.yaml"),
        },
        "confidence": confidence,
        "metrics": summary,
        "artifacts": artifact_status,
        "findings": findings,
        "improvementItems": [
            dict(item) for item in findings if item["type"] in {"improvement", "expected-weakness"}
        ],
    }


def _artifact_status(output_dir: Path, expected_artifacts: tuple[str, ...]) -> list[dict[str, str]]:
    names = list(
        dict.fromkeys([*expected_artifacts, "contract-validation.yaml", "handoff-review.html"])
    )
    return [
        {
            "name": name,
            "status": "present" if (output_dir / name).exists() else "missing",
        }
        for name in names
    ]


def _finding(kind: str, area: str, message: str) -> dict[str, str]:
    return {"type": kind, "area": area, "message": message}


def _confidence_status(findings: list[dict[str, str]], area: str) -> str:
    area_findings = [item for item in findings if item["area"] == area]
    if any(item["type"] == "fail" for item in area_findings):
        return "fail"
    if any(item["type"] == "improvement" for item in area_findings):
        return "improvement"
    if any(item["type"] == "expected-weakness" for item in area_findings):
        return "expected-weakness"
    return "pass"
