"""Artifact lifecycle helpers for compile orchestration."""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path
from typing import Any

from .generator import generate_all
from .patterns import GLOBAL_REGISTRY
from .validator import Violation
from .yaml_utils import write_yaml_artifact

INTENT_ARTIFACT_HEADER = (
    "# yaml-language-server: $schema=none\n"
    "# Generated by intent-engine — intent artifact, not deployable configuration.\n"
)


def write_intent_yaml_artifact(output_dir: Path, name: str, data: Any) -> None:
    write_yaml_artifact(output_dir / name, data, INTENT_ARTIFACT_HEADER)


def validate_generated_violations(input_dir: Path, pattern: str = "aws-lza") -> list[Violation]:
    violations: list[Violation] = []
    from .contracts import (
        CONTEXT_MANIFEST_CONTRACT,
        HANDOFF_PLAN_CONTRACT,
        PLAN_READY_BUNDLE_CONTRACT,
        ContractValidator,
    )

    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    for fname in pattern_obj.expected_artifacts():
        if not (input_dir / fname).exists():
            violations.append(
                Violation(
                    code="REQUIRED_ARTIFACT_MISSING",
                    message=f"Missing required file: {fname}",
                )
            )

    # Run contract-driven artifact validators.
    for contract in pattern_obj.contracts:
        violations.extend(ContractValidator(contract).validate_artifacts(input_dir))
    if pattern_obj.contracts:
        violations.extend(ContractValidator(HANDOFF_PLAN_CONTRACT).validate_artifacts(input_dir))
    violations.extend(ContractValidator(CONTEXT_MANIFEST_CONTRACT).validate_artifacts(input_dir))
    if pattern_obj.plan_ready:
        violations.extend(
            ContractValidator(PLAN_READY_BUNDLE_CONTRACT).validate_artifacts(input_dir)
        )

    deduped: list[Violation] = []
    seen_messages: set[str] = set()
    for violation in violations:
        if violation.message in seen_messages:
            continue
        seen_messages.add(violation.message)
        deduped.append(violation)
    return deduped


def validate_generated(input_dir: Path, pattern: str = "aws-lza") -> list[str]:
    return [violation.message for violation in validate_generated_violations(input_dir, pattern)]


def artifact_contract_violations(output_dir: Path, pattern: str) -> list[Violation]:
    return [
        Violation(
            code=f"ARTIFACT_CONTRACT_{violation.code}",
            message=violation.message,
        )
        for violation in validate_generated_violations(output_dir, pattern)
    ]


def generated_artifact_names(pattern: str) -> set[str]:
    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    return {
        *pattern_obj.expected_artifacts(),
        "decision-report.yaml",
        "llm-trace-summary.yaml",
        "model-benchmark.yaml",
        "contract-validation.yaml",
        "handoff-review.html",
        "missing-inputs.yaml",
        "input-diff-report.yaml",
        "incremental-compile-report.yaml",
    }


def remove_generated_artifacts(output_dir: Path, pattern: str) -> None:
    if not output_dir.exists():
        return
    for name in generated_artifact_names(pattern):
        path = output_dir / name
        if path.is_symlink():
            path.unlink()
        elif path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()


def promote_generated_artifacts(staging_dir: Path, output_dir: Path, pattern: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    remove_generated_artifacts(output_dir, pattern)
    for source in staging_dir.iterdir():
        destination = output_dir / source.name
        if source.is_dir():
            shutil.copytree(source, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(source, destination)


def generate_validated_artifacts(
    payload: Any,
    output_dir: Path,
    pattern: str,
    *,
    extra_artifacts: dict[str, Any] | None = None,
) -> list[Violation]:
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix=".intent-engine-generate-",
        dir=output_dir.parent,
    ) as staging:
        staging_dir = Path(staging)
        generate_all(payload, staging_dir)
        for name, data in (extra_artifacts or {}).items():
            write_intent_yaml_artifact(staging_dir, name, data)
        violations = artifact_contract_violations(staging_dir, pattern)
        if violations:
            remove_generated_artifacts(output_dir, pattern)
            return violations
        promote_generated_artifacts(staging_dir, output_dir, pattern)
    return []
