"""Orchestrator: drives the decision engine flow — extract, normalize, validate, generate."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import ruamel.yaml

from .extractor import Extractor, LLMGraphResult
from .generator import generate_all
from .interview import InterviewEngine
from .llm_caller import LLMCaller, LLMEvidenceStore
from .markdown_extractor import (
    extract_entities_from_markdown,
    extract_from_markdown_with_diagnostics,
)
from .model_introspection import append_to_list_field, merge_into_list_field
from .normalizer import normalize
from .patterns import GLOBAL_REGISTRY
from .validator import Violation, validate


class CompileError(Exception):
    def __init__(self, violations: list[Violation], readiness: dict[str, Any] | None = None):
        self.violations = violations
        self.readiness = readiness or {}
        msgs = "; ".join(f"{v.code}: {v.message}" for v in violations)
        super().__init__(msgs)


def _merge_extracted_entities(intent: Any, entities: dict[str, list[dict[str, Any]]]) -> None:
    """Merge deterministic entities into intent without duplicating named items."""
    for entity_type in ("ous", "accounts", "workloads"):
        if not hasattr(intent, entity_type):
            continue
        for item in entities.get(entity_type, []):
            if not merge_into_list_field(intent, entity_type, item):
                append_to_list_field(intent, entity_type, item)


def _build_payload(
    intent: Any,
    pattern: str,
    decisions: dict[str, Any] | None = None,
    design_doc_data: dict[str, Any] | None = None,
    extraction_summary: dict[str, Any] | None = None,
    deployment_readiness: dict[str, Any] | None = None,
) -> Any:
    """Wrap intent in IaCIntentPayload with design doc and module inputs."""
    from .module_mapping import DesignDocument, IaCIntentPayload, map_intent_to_modules

    design_doc = DesignDocument()
    if design_doc_data:
        design_doc.project_name = design_doc_data.get("project_name", "")
        design_doc.business_justification = design_doc_data.get("business_justification", "")
        design_doc.estimated_tier = design_doc_data.get("estimated_tier", "")
        design_doc.compliance_tags = design_doc_data.get("compliance_tags", [])

    module_inputs = map_intent_to_modules(intent, pattern)
    return IaCIntentPayload(
        design_doc=design_doc,
        module_inputs=module_inputs,
        intent=intent,
        pattern=pattern,
        decisions=decisions or {},
        extraction_summary=extraction_summary or {},
        deployment_readiness=deployment_readiness or {},
    )


def _yaml_dump(data: Any) -> str:
    yaml = ruamel.yaml.YAML()
    yaml.default_flow_style = False
    yaml.indent(mapping=2, sequence=4, offset=2)
    from io import StringIO

    buf = StringIO()
    yaml.dump(data, buf)
    return "\n".join(line.rstrip() for line in buf.getvalue().splitlines()) + "\n"


def _write_yaml_artifact(output_dir: Path, name: str, data: Any) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    header = (
        "# yaml-language-server: $schema=none\n"
        "# Generated by intent-engine — intent artifact, not deployable configuration.\n"
    )
    (output_dir / name).write_text(header + _yaml_dump(data))


def _to_builtin(value: Any) -> Any:
    if hasattr(value, "value"):
        return _to_builtin(value.value)
    if isinstance(value, dict):
        return {str(k): _to_builtin(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_to_builtin(item) for item in value]
    return value


def _without_locked_decisions(
    decisions: dict[str, Any],
    locked_keys: set[str],
) -> dict[str, Any]:
    return {key: value for key, value in decisions.items() if key not in locked_keys}


def _gap_is_resolved(graph, gap: Any) -> bool:
    key = _finding_key(gap)
    if key is None:
        return False
    value = graph.get(key)
    return value is not None and str(value).strip() != ""


def _blocking_gaps(graph, gaps: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        gap
        for gap in gaps
        if isinstance(gap, dict)
        and _finding_targets_requirement(graph, gap)
        and not _gap_is_resolved(graph, gap)
    ]


def _finding_key(finding: Any) -> str | None:
    if not isinstance(finding, dict):
        return None
    key = finding.get("key")
    if not isinstance(key, str) or not key:
        return None
    return key


def _finding_targets_requirement(graph, finding: Any) -> bool:
    key = _finding_key(finding)
    if key is None or not _graph_has_requirement(graph, key):
        return False
    is_applicable = getattr(graph, "is_applicable", None)
    if callable(is_applicable) and not is_applicable(key):
        return False
    is_blocked = getattr(graph, "is_blocked", None)
    if callable(is_blocked) and is_blocked(key):
        return False
    return True


def _graph_has_requirement(graph, key: str) -> bool:
    has_requirement = getattr(graph, "has_requirement", None)
    if callable(has_requirement):
        return bool(has_requirement(key))
    requirements = getattr(graph, "_requirements", {})
    return key in requirements


def _blocking_contradictions(graph, contradictions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        contradiction
        for contradiction in contradictions
        if isinstance(contradiction, dict) and _finding_targets_requirement(graph, contradiction)
    ]


def _llm_result_violations(graph, llm_result: LLMGraphResult) -> list[Violation]:
    violations: list[Violation] = []
    for gap in _blocking_gaps(graph, llm_result.gaps):
        key = gap.get("key", "unknown") if isinstance(gap, dict) else "unknown"
        reason = gap.get("reason", "missing decision") if isinstance(gap, dict) else str(gap)
        violations.append(
            Violation(
                code=f"LLM_GAP_{str(key).upper()}",
                message=f"LLM reported missing decision '{key}': {reason}",
            )
        )
    for contradiction in _blocking_contradictions(graph, llm_result.contradictions):
        key = contradiction.get("key", "unknown")
        reason = contradiction.get("reason", "contradiction")
        details = contradiction.get("details", "")
        suffix = f" ({details})" if details else ""
        violations.append(
            Violation(
                code=f"LLM_CONTRADICTION_{str(key).upper()}",
                message=f"LLM reported conflicting decision '{key}': {reason}{suffix}",
            )
        )
    return violations


def _markdown_contradiction_violations(
    contradictions: list[dict[str, Any]],
) -> list[Violation]:
    violations: list[Violation] = []
    for contradiction in contradictions:
        key = contradiction.get("key", "unknown")
        reason = contradiction.get("reason", "conflicting structured Markdown values")
        details = contradiction.get("details", "")
        suffix = f" ({details})" if details else ""
        violations.append(
            Violation(
                code=f"MARKDOWN_CONTRADICTION_{str(key).upper()}",
                message=f"Markdown reported conflicting decision '{key}': {reason}{suffix}",
            )
        )
    return violations


def _graph_missing_decisions(graph) -> list[dict[str, Any]]:
    from .requirements import RequirementStatus

    missing: list[dict[str, Any]] = []
    for key, req in graph._requirements.items():
        if not req.required_when_applicable:
            continue
        if not graph.is_applicable(key) or graph.is_blocked(key):
            continue
        status = graph.status(key)
        value = graph.get(key)
        if (
            status in (RequirementStatus.DECIDED, RequirementStatus.DEFAULTED)
            and str(value or "").strip()
        ):
            continue
        missing.append(
            {
                "key": key,
                "label": req.label,
                "reason": req.violation_message or f"{req.label} is required when applicable.",
                "question": req.question,
            }
        )
    return missing


def _violation_conflicts(violations: list[Violation]) -> list[dict[str, str]]:
    conflicts: list[dict[str, str]] = []
    for violation in violations:
        if violation.code.endswith("_REQUIRED") or "REQUIRED" in violation.code:
            continue
        if violation.code.startswith("LLM_GAP_"):
            continue
        if violation.code.startswith("LLM_CONTRADICTION_"):
            continue
        conflicts.append({"code": violation.code, "reason": violation.message})
    return conflicts


def _build_deployment_readiness(
    graph,
    violations: list[Violation],
    llm_result: LLMGraphResult,
) -> dict[str, Any]:
    missing = _graph_missing_decisions(graph)
    conflicts = _violation_conflicts(violations)
    llm_gaps = _blocking_gaps(graph, llm_result.gaps)
    llm_contradictions = _blocking_contradictions(graph, llm_result.contradictions)
    blockers = [{"code": v.code, "message": v.message} for v in violations]
    deployment_allowed = not blockers
    return {
        "deploymentAllowed": deployment_allowed,
        "status": "ready" if deployment_allowed else "blocked",
        "summary": (
            "Ready for handoff."
            if deployment_allowed
            else "Cannot deploy yet; missing or conflicting decisions must be resolved."
        ),
        "blockers": blockers,
        "missingDecisions": missing + llm_gaps,
        "conflictingDecisions": conflicts + llm_contradictions,
        "safeHandoffPath": [
            "Do not run downstream deployment from this output while status is blocked.",
            "Resolve missing and conflicting decisions with the owning architect/platform team.",
            "Re-run compile and preserve decision-report.yaml plus lineage artifacts for handoff.",
            "Use existing accelerator/module deployment path only after deploymentAllowed is true.",
        ],
    }


def _build_extraction_summary(
    *,
    pattern: str,
    evidence_store: LLMEvidenceStore | None,
    raw_evidence_path: Path | None,
    markdown_decisions: dict[str, Any],
    markdown_contradictions: list[dict[str, Any]],
    llm_result: LLMGraphResult,
    readiness: dict[str, Any],
    applied_decisions: dict[str, list[str]],
    accepted_decisions: dict[str, Any],
    graph,
) -> dict[str, Any]:
    calls = []
    evidence_entries = evidence_store.entries if evidence_store is not None else []
    for entry in evidence_entries:
        calls.append(
            {
                "provider": _readable_provider(entry.get("backend", "unknown")),
                "model": entry.get("model", "unknown"),
                "latencyMs": round(float(entry.get("latency_ms", 0) or 0), 1),
                "parseError": entry.get("parse_error"),
            }
        )
    first = calls[0] if calls else {}
    blocking_gaps = _blocking_gaps(graph, llm_result.gaps)
    resolved_gaps = [
        gap for gap in llm_result.gaps if isinstance(gap, dict) and _gap_is_resolved(graph, gap)
    ]
    blocking_contradictions = _blocking_contradictions(graph, llm_result.contradictions)
    raw_evidence = _raw_evidence_status(raw_evidence_path, evidence_store)
    return {
        "pattern": pattern,
        "provider": first.get("provider", "none"),
        "model": first.get("model", "none") or "none",
        "callCount": len(calls),
        "calls": calls,
        "markdownDecisions": markdown_decisions,
        "markdownContradictions": markdown_contradictions,
        "rawLlmDecisions": llm_result.decisions,
        "rawLlmSignalDecisions": llm_result.signal_decisions,
        "acceptedDecisions": _to_builtin(accepted_decisions),
        "appliedDecisions": applied_decisions,
        "signalDecisions": llm_result.signal_decisions,
        "gaps": {
            "resolved": resolved_gaps,
            "blocking": blocking_gaps,
            "raw": llm_result.gaps,
        },
        "contradictions": {
            "blocking": blocking_contradictions,
            "raw": llm_result.contradictions,
        },
        "deploymentReadiness": {
            "deploymentAllowed": readiness["deploymentAllowed"],
            "status": readiness["status"],
            "blockerCount": len(readiness["blockers"]),
            "blockingGapCount": len(blocking_gaps),
            "blockingContradictionCount": len(blocking_contradictions),
        },
        "rawEvidence": raw_evidence,
    }


def _readable_provider(provider: Any) -> str:
    value = str(provider or "unknown")
    if value == "OpenAICompatibleBackend":
        return "openai-compatible"
    if value.endswith("Backend"):
        value = value[: -len("Backend")]
    return value.replace("_", "-").lower() or "unknown"


def _raw_evidence_status(
    raw_evidence_path: Path | None,
    evidence_store: LLMEvidenceStore | None,
) -> dict[str, str]:
    if raw_evidence_path is None:
        return {"path": "not-requested", "status": "not-requested"}
    if evidence_store is None or not evidence_store.entries:
        return {"path": str(raw_evidence_path), "status": "requested-empty"}
    return {"path": str(raw_evidence_path), "status": "requested"}


def _write_failed_compile_artifacts(
    output_dir: Path,
    pattern: str,
    graph,
    readiness: dict[str, Any],
    extraction_summary: dict[str, Any],
) -> None:
    _write_yaml_artifact(
        output_dir,
        "decision-report.yaml",
        {
            "pattern": pattern,
            "decisions": _to_builtin(graph.typed_decisions()),
            "deploymentReadiness": readiness,
        },
    )
    _write_yaml_artifact(output_dir, "llm-trace-summary.yaml", extraction_summary)


class LLMContextProvider:
    """Non-deterministic layer: the LLM reads prose and traverses the requirement graph.

    This is the *intent understanding* layer. The LLM may hallucinate, miss,
    or misread — that is expected and handled downstream by the deterministic
    harness.
    """

    def __init__(
        self,
        prose: str,
        graph,
        llm_caller: LLMCaller | None = None,
        evidence_store: LLMEvidenceStore | None = None,
    ) -> None:
        self.prose = prose
        self.graph = graph
        self.llm_caller = llm_caller
        self.evidence_store = evidence_store
        self.extractor = Extractor(graph=graph)

    def run(self) -> LLMGraphResult:
        """Run LLM graph traversal and return structured result.

        When no LLM is available, returns an empty result — the harness
        will apply defaults and fill gaps deterministically.
        """
        if self.llm_caller is None:
            return LLMGraphResult()

        prompt = self.extractor.build_prompt(self.prose)
        response, evidence = self.llm_caller.call(prompt)
        if self.evidence_store is not None:
            self.evidence_store.record(evidence)

        result = self.extractor.parse_response(response)
        return result


def compile_design(
    input_path: Path,
    output_dir: Path,
    graph=None,
    llm_caller: LLMCaller | None = None,
    evidence_store: LLMEvidenceStore | None = None,
    raw_evidence_path: Path | None = None,
    dry_run: bool = False,
    pattern: str = "aws-lza",
) -> None:
    """Extract, normalize, validate, and generate from a design doc.

    Two-layer architecture:
      1. Non-deterministic: LLMContextProvider reads prose and traverses graph
      2. Deterministic: harness applies gates, cascades, defaults, validates,
         generates artifacts, and records audit trail
    """
    if input_path.is_dir():
        texts = []
        for f in sorted(input_path.glob("*.md")):
            texts.append(f.read_text())
        text = "\n---\n".join(texts)
    else:
        text = input_path.read_text()

    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    if graph is None:
        graph = pattern_obj.create_graph()

    # ------------------------------------------------------------------
    # Layer 0: Deterministic Markdown pre-processing
    # ------------------------------------------------------------------
    markdown_result = extract_from_markdown_with_diagnostics(text, graph)
    markdown_decisions = markdown_result.decisions
    markdown_entities = extract_entities_from_markdown(text)
    applied_decisions: dict[str, list[str]] = {
        "markdown": [],
        "llm": [],
        "signals": [],
        "defaults": [],
    }
    if markdown_decisions:
        applied_decisions["markdown"] = graph.apply_decisions(markdown_decisions)

    # ------------------------------------------------------------------
    # Layer 1: Non-deterministic intent understanding (LLM)
    # ------------------------------------------------------------------
    llm_result = LLMContextProvider(
        prose=text,
        graph=graph,
        llm_caller=llm_caller,
        evidence_store=evidence_store,
    ).run()

    # ------------------------------------------------------------------
    # Layer 2: Deterministic harness processing
    # ------------------------------------------------------------------
    # 2a. Apply LLM-extracted decisions to the graph (gates + cascade)
    locked_decision_keys = set(applied_decisions["markdown"])
    if llm_result.decisions:
        llm_decisions = _without_locked_decisions(llm_result.decisions, locked_decision_keys)
        applied_decisions["llm"] = graph.apply_decisions(llm_decisions)
        locked_decision_keys.update(applied_decisions["llm"])

    # 2b. Apply signal-triggered decisions
    if llm_result.signal_decisions:
        signal_decisions = _without_locked_decisions(
            llm_result.signal_decisions,
            locked_decision_keys,
        )
        applied_decisions["signals"] = graph.apply_decisions(signal_decisions)

    # 2c. Fill remaining gaps with defaults
    graph.apply_defaults_for_remaining()
    applied_decisions["defaults"] = [
        str(entry["key"]) for entry in graph.audit_log() if entry.get("how") == "defaulted"
    ]

    # 2d. Build intent from LLM decisions (handles complex nested objects)
    # then overlay graph cascade decisions onto the same intent
    if llm_result.decisions or llm_result.signal_decisions:
        extractor = Extractor(graph=graph, pattern=pattern)
        intent = llm_result.to_intent(extractor)
    else:
        intent = pattern_obj.intent_factory()
    # Deterministic entities backfill items that small models often omit.
    _merge_extracted_entities(intent, markdown_entities)
    # Apply graph cascades (topology -> network.topology, etc.)
    graph.apply_to_intent(intent)

    # 2e. Apply normalizer guardrails
    if pattern_obj.normalizer is not None:
        intent = pattern_obj.normalizer(intent)
    else:
        intent = normalize(intent)

    # 2f. Validate fail-closed (graph-driven when available)
    violations = validate(intent, graph=graph, extra_validators=pattern_obj.validators)
    violations.extend(_markdown_contradiction_violations(markdown_result.contradictions))
    violations.extend(_llm_result_violations(graph, llm_result))
    readiness = _build_deployment_readiness(graph, violations, llm_result)
    extraction_summary = _build_extraction_summary(
        pattern=pattern,
        evidence_store=evidence_store,
        raw_evidence_path=raw_evidence_path,
        markdown_decisions=markdown_decisions,
        markdown_contradictions=markdown_result.contradictions,
        llm_result=llm_result,
        readiness=readiness,
        applied_decisions=applied_decisions,
        accepted_decisions=graph.typed_decisions(),
        graph=graph,
    )
    if violations:
        if not dry_run:
            _write_failed_compile_artifacts(
                output_dir,
                pattern,
                graph,
                readiness,
                extraction_summary,
            )
        raise CompileError(violations, readiness=readiness)

    if dry_run:
        return

    # 2g. Generate artifacts
    payload = _build_payload(
        intent,
        pattern,
        graph.typed_decisions(),
        llm_result.design_doc,
        extraction_summary=extraction_summary,
        deployment_readiness=readiness,
    )
    generate_all(payload, output_dir, pattern=pattern)


def compile_from_interview(
    decisions: dict[str, str],
    output_dir: Path,
    accept_defaults: bool = True,
    pattern: str = "aws-lza",
) -> None:
    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    graph = pattern_obj.create_graph()
    engine = InterviewEngine(graph, pattern=pattern)
    engine.run_from_decisions(decisions)
    if accept_defaults:
        engine.apply_defaults_for_remaining()
    intent = engine.to_intent()
    if pattern_obj.normalizer is not None:
        intent = pattern_obj.normalizer(intent)
    else:
        intent = normalize(intent)
    violations = validate(intent, graph=graph, extra_validators=pattern_obj.validators)
    if violations:
        raise CompileError(violations)
    generate_all(
        _build_payload(intent, pattern, graph.typed_decisions()),
        output_dir,
        pattern=pattern,
    )

    # Write decision audit trail for traceability
    audit = graph.audit_log()
    if audit:
        import ruamel.yaml

        yaml = ruamel.yaml.YAML()
        yaml.default_flow_style = False
        audit_path = output_dir / "decision-audit.yaml"
        with open(audit_path, "w") as f:
            yaml.dump({"auditTrail": audit}, f)


def validate_generated_violations(input_dir: Path, pattern: str = "aws-lza") -> list[Violation]:
    violations: list[Violation] = []
    from .contracts import HANDOFF_PLAN_CONTRACT, ContractValidator
    from .patterns import GLOBAL_REGISTRY

    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    for fname in pattern_obj.expected_artifacts():
        if not (input_dir / fname).exists():
            violations.append(
                Violation(
                    code="REQUIRED_ARTIFACT_MISSING",
                    message=f"Missing required file: {fname}",
                )
            )

    # Run contract-driven artifact validators
    for contract in pattern_obj.contracts:
        violations.extend(ContractValidator(contract).validate_artifacts(input_dir))
    if pattern_obj.contracts:
        violations.extend(ContractValidator(HANDOFF_PLAN_CONTRACT).validate_artifacts(input_dir))

    # Run pattern-specific artifact validators
    for validator in pattern_obj.artifact_validators:
        for message in validator(input_dir):
            violations.append(Violation(code="ARTIFACT_VALIDATION_FAILED", message=message))

    deduped: list[Violation] = []
    seen_messages: set[str] = set()
    for violation in violations:
        if violation.message in seen_messages:
            continue
        seen_messages.add(violation.message)
        deduped.append(violation)
    return deduped


def validate_generated(input_dir: Path, pattern: str = "aws-lza") -> list[str]:
    return [violation.message for violation in validate_generated_violations(input_dir, pattern)]


def review_reports(before_path: Path, after_path: Path) -> dict:
    """Diff two decision reports and return structured review."""
    yaml_loader = ruamel.yaml.YAML(typ="safe")

    with open(before_path) as f:
        before = yaml_loader.load(f) or {}
    with open(after_path) as f:
        after = yaml_loader.load(f) or {}

    result: dict = {"changes": [], "added": [], "removed": [], "audit": {}}

    def _flatten(d: dict, prefix: str = "") -> dict[str, Any]:
        items: dict[str, Any] = {}
        for k, v in d.items():
            key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict) and k not in (
                "wellArchitectedCoverage",
                "decisionAuditTrail",
            ):
                items.update(_flatten(v, key))
            elif isinstance(v, list):
                items[key] = sorted(v) if v and not isinstance(v[0], dict) else v
            elif k == "wellArchitectedCoverage":
                pass
            elif k == "decisionAuditTrail":
                pass
            else:
                items[key] = v
        return items

    flat_before = _flatten(before)
    flat_after = _flatten(after)

    all_keys = set(flat_before) | set(flat_after)

    for key in sorted(all_keys):
        b_val = flat_before.get(key)
        a_val = flat_after.get(key)
        if key not in flat_before:
            result["added"].append({"key": key, "value": a_val})
        elif key not in flat_after:
            result["removed"].append({"key": key, "value": b_val})
        elif b_val != a_val:
            result["changes"].append({"key": key, "before": b_val, "after": a_val})

    # WA coverage diff
    b_wa = before.get("wellArchitectedCoverage", {}) or {}
    a_wa = after.get("wellArchitectedCoverage", {}) or {}
    result["wellArchitectedCoverage"] = {"before": b_wa, "after": a_wa}

    # Audit trail diff
    b_audit = before.get("decisionAuditTrail", []) or []
    a_audit = after.get("decisionAuditTrail", []) or []
    result["audit"] = {
        "before_count": len(b_audit),
        "after_count": len(a_audit),
        "new_entries": a_audit[len(b_audit) :] if len(a_audit) > len(b_audit) else [],
    }

    return result


def _build_section_map(pattern: str, graph) -> dict[str, tuple[str, str | None]]:
    """Build a section map from pattern metadata + category fallback.

    New requirements automatically appear in templates under their category
    if no explicit mapping is provided.
    """
    from .patterns import GLOBAL_REGISTRY

    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    section_map: dict[str, tuple[str, str | None]] = dict(pattern_obj.section_map)

    # Fallback: derive section from requirement category
    _CATEGORY_TO_SECTION: dict[str, str] = {
        "organization": "Region",
        "network": "Network",
        "security": "Security",
        "compliance": "Security",
        "hybrid": "Hybrid Connectivity",
        "cicd": "CI/CD",
        "cost": "Network",
        "workload": "Workloads",
        "general": "General",
    }
    for key, req in graph._requirements.items():
        if key in section_map:
            continue
        category = req.category or "general"
        section_name = _CATEGORY_TO_SECTION.get(category)
        if section_name:
            section_map[key] = (section_name, req.key)

    return section_map


def generate_template(pattern: str = "aws-lza") -> str:
    """Generate a Markdown design doc scaffold from a pattern."""
    from .patterns import GLOBAL_REGISTRY

    pattern_obj = GLOBAL_REGISTRY.get(pattern)
    graph = pattern_obj.create_graph()

    section_map = _build_section_map(pattern, graph)

    sections_content: dict[str, list[tuple[str, Any, str | None]]] = {}
    for key, req in graph._requirements.items():
        info = section_map.get(key)
        if info is None:
            continue
        section_name, field_name = info
        sections_content.setdefault(section_name, []).append((key, req, field_name))

    lines: list[str] = []
    lines.append(f"# Design Document — {pattern} pattern")
    lines.append("#")
    lines.append("# Generated by intent-engine template. Fill in your decisions below.")
    lines.append("# Lines starting with # are comments. Uncomment and edit to set values.")
    lines.append("")

    section_order = pattern_obj.section_order or []
    free_form_examples = pattern_obj.free_form_examples or {}

    for section_name in section_order:
        has_fields = section_name in sections_content
        has_examples = section_name in free_form_examples
        if not has_fields and not has_examples:
            continue

        lines.append(f"## {section_name}")
        lines.append("")

        if section_name in free_form_examples:
            for example in free_form_examples[section_name]:
                lines.append(f"# - {example}")
            lines.append("")
            # Only skip field-based content if there are no requirements for this section
            if section_name not in sections_content:
                continue

        for key, req, field_name in sections_content.get(section_name, []):
            if req.applies_if:
                for cond_key, cond_vals in req.applies_if.items():
                    lines.append(f"# Only when {cond_key} is one of: {', '.join(cond_vals)}")

            lines.append(f"# {req.question}")
            if req.options:
                lines.append(f"# Options: {', '.join(req.options)}")
            if req.default:
                lines.append(f"# Default: {req.default}")

            if field_name is None:
                # Topology field: show default uncommented, alternatives commented
                if req.options:
                    for opt in req.options:
                        if opt == req.default:
                            lines.append(f"- {opt}")
                        else:
                            lines.append(f"# - {opt}")
                elif req.default:
                    lines.append(f"- {req.default}")
            else:
                line = f"- {field_name}: "
                if req.default:
                    line += req.default
                lines.append(line)

            lines.append("")

    return "\n".join(lines)


def explain_report(report_path: Path) -> str:
    yaml_loader = ruamel.yaml.YAML(typ="safe")
    with open(report_path) as f:
        report = yaml_loader.load(f) or {}

    lines = ["=== Decision Report ===", ""]

    def _render(data: Any, indent: int = 0) -> None:
        prefix = "  " * indent
        if isinstance(data, dict):
            for k, v in data.items():
                if isinstance(v, dict | list):
                    lines.append(f"{prefix}{k}:")
                    _render(v, indent + 1)
                else:
                    lines.append(f"{prefix}{k}: {v}")
        elif isinstance(data, list):
            for item in data:
                if isinstance(item, dict):
                    lines.append(f"{prefix}-")
                    _render(item, indent + 1)
                else:
                    lines.append(f"{prefix}- {item}")
        else:
            lines.append(f"{prefix}{data}")

    _render(report)
    return "\n".join(lines)
