"""Generate intent artifacts from validated intent.

Produces decision reports, contract handoff artifacts, lineage, runbooks, and
module input files that engineers use alongside their IaC modules.

Core artifact generators are fixed here. Pattern-specific generators live on
their owning Pattern.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .module_mapping import IaCIntentPayload
from .patterns import PatternGenerator
from .policy import policy_pack_inventory, policy_packs_to_dict
from .replay import contract_digest, replay_artifact_digest
from .yaml_utils import write_yaml_artifact

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write(output_dir: Path, name: str, data: Any, schema_version: str | None = None) -> None:
    if schema_version and isinstance(data, dict):
        data = {"schemaVersion": schema_version, **data}
    header = (
        "# yaml-language-server: $schema=none\n"
        "# Generated by intent-engine — intent artifact, "
        "not deployable configuration.\n"
    )
    write_yaml_artifact(output_dir / name, data, header)


def generate_all(payload: IaCIntentPayload, output_dir: Path) -> None:
    from .patterns import GLOBAL_REGISTRY as PATTERN_REGISTRY

    pattern_generators: list[PatternGenerator] = []
    if payload.pattern:
        pattern = PATTERN_REGISTRY.get(payload.pattern)
        if payload.intent is not None and not isinstance(payload.intent, pattern.intent_factory):
            raise TypeError(
                f"Pattern '{payload.pattern}' requires {pattern.intent_factory.__name__}, "
                f"got {type(payload.intent).__name__}."
            )
        pattern_generators = pattern.generators
    generators = [*CORE_GENERATORS, *pattern_generators]
    for generator in sorted(generators, key=lambda item: item.priority):
        before = _artifact_fingerprints(output_dir)
        generator.fn(payload, output_dir)
        after = _artifact_fingerprints(output_dir)
        changed = {
            path for path in before.keys() | after.keys() if before.get(path) != after.get(path)
        }
        unexpected = sorted(changed - set(generator.outputs))
        if unexpected:
            raise ValueError(
                f"Generator '{generator.name}' changed undeclared artifacts: "
                f"{', '.join(unexpected)}."
            )


def _artifact_fingerprints(output_dir: Path) -> dict[str, str]:
    if not output_dir.exists():
        return {}
    fingerprints: dict[str, str] = {}
    for item in output_dir.rglob("*"):
        relative = item.relative_to(output_dir).as_posix()
        if item.is_symlink():
            raise ValueError(f"Generated artifact must not be a symlink: {relative}.")
        if item.is_file():
            fingerprints[relative] = hashlib.sha256(item.read_bytes()).hexdigest()
    return fingerprints


def gen_module_inputs(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write module-inputs.yaml when module mappings exist."""
    inputs = payload.module_inputs
    if not inputs:
        return
    data = {
        "moduleInputs": [{"moduleName": mi.module_name, "variables": mi.variables} for mi in inputs]
    }
    _write(output_dir, "module-inputs.yaml", data)


def _hcl_value(value: Any) -> str:
    """Format a Python value as an HCL literal for .tfvars."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, list):
        items = ", ".join(_hcl_value(v) for v in value)
        return f"[{items}]"
    if isinstance(value, dict):
        # Flatten nested dicts as dotted keys in the caller; this fallback
        # writes a simple HCL object literal — rarely needed for tfvars.
        pairs = ", ".join(f"{k} = {_hcl_value(v)}" for k, v in value.items())
        return "{" + pairs + "}"
    # Strings (and anything else) get quoted
    return json.dumps(str(value))


def gen_tfvars(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write terraform.tfvars from module_inputs when mappings exist."""
    inputs = payload.module_inputs
    if not inputs:
        return

    lines: list[str] = []
    lines.append("# Generated by intent-engine — Terraform variables from module inputs.")
    lines.append("")

    for mi in inputs:
        lines.append(f"# Module: {mi.module_name}")
        key_width = max((len(key) for key in mi.variables), default=0)
        for key, value in mi.variables.items():
            lines.append(f"{key.ljust(key_width)} = {_hcl_value(value)}")
        lines.append("")

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "terraform.tfvars").write_text("\n".join(lines))


def gen_sample_recommendations(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write sample-recommendations.yaml when pattern-backed samples exist."""
    pattern = payload.pattern
    decisions = payload.decisions
    if not pattern or not decisions:
        return

    from .patterns import GLOBAL_REGISTRY as PATTERN_REGISTRY
    from .sample_config import SampleConfig

    matches = PATTERN_REGISTRY.find_sample_matches(decisions, pattern=pattern, limit=3)
    if not matches:
        return

    data = {
        "pattern": pattern,
        "currentDecisions": SampleConfig.to_builtin(decisions),
        "recommendations": [
            {
                "name": match.sample.name,
                "description": match.sample.description,
                "version": match.sample.version,
                "releaseDate": match.sample.release_date,
                "sourceUrl": match.sample.source_url,
                "sourceContract": match.sample.source_contract,
                "upstreamVariant": match.sample.upstream_variant,
                "tags": match.sample.tags,
                "sameDecisionCount": match.same_count,
                "differentDecisionCount": match.different_count,
                "missingDecisionCount": match.missing_count,
                "totalSampleDecisions": match.total_sample_decisions,
                "sameDecisions": sorted(match.diff["same"].keys()),
                "differentDecisions": SampleConfig.to_builtin(match.diff["different"]),
                "missingDecisions": SampleConfig.to_builtin(match.diff["missing_in_current"]),
                "extraCurrentDecisions": SampleConfig.to_builtin(match.diff["extra_in_current"]),
            }
            for match in matches
        ],
    }
    _write(output_dir, "sample-recommendations.yaml", data)


def gen_llm_trace_summary(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write a lean summary of extraction evidence when compile captured it."""
    summary = payload.extraction_summary
    if not summary:
        return
    _write(output_dir, "llm-trace-summary.yaml", summary)


def gen_model_benchmark(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write model behavior rollups from the extraction trace."""
    summary = payload.extraction_summary
    if not summary:
        return
    from .observability import build_model_benchmark

    _write(output_dir, "model-benchmark.yaml", build_model_benchmark(summary))


def gen_decision_audit(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write the graph decision audit trail captured during compile."""
    audit = payload.decision_audit
    write_yaml_artifact(
        output_dir / "decision-audit.yaml",
        {"auditTrail": audit},
        "",
        indent=False,
    )


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _model_name(model: Any) -> str:
    if isinstance(model, type):
        return f"{model.__module__}.{model.__name__}"
    return type(model).__name__


def gen_context_manifest(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write the code-owned context inventory used to build this handoff bundle."""
    pattern = payload.pattern
    if not pattern:
        return

    from .patterns import GLOBAL_REGISTRY as PATTERN_REGISTRY

    pattern_obj = PATTERN_REGISTRY.get(pattern)
    graph = pattern_obj.create_graph()
    prompt_context = " ".join(pattern_obj.prompt_context.split())
    decisions = payload.decisions
    extraction_summary = payload.extraction_summary
    target_capability_report = payload.target_capability_report
    module_inputs = payload.module_inputs
    samples = sorted(PATTERN_REGISTRY.get(pattern).samples, key=lambda sample: sample.name)

    data = {
        "pattern": pattern,
        "boundary": (
            "LLM context is advisory input. Requirement graphs, target contracts, "
            "validators, samples, and review gates own acceptance and handoff."
        ),
        "contextInventory": {
            "pattern": {
                "name": pattern_obj.name,
                "description": pattern_obj.description,
                "intentModel": _model_name(pattern_obj.intent_factory),
            },
            "promptContext": {
                "present": bool(prompt_context),
                "sha256": _sha256_text(prompt_context),
                "wordCount": len(prompt_context.split()),
                "text": prompt_context,
            },
            "requirementGraph": {
                "nodeCount": len(graph._requirements),
                "edgeCount": graph.edge_count(),
                "requirements": [
                    {
                        "key": key,
                        "category": req.category,
                        "targetField": req.target_field,
                        "targetType": req.target_type,
                        "requiredWhenApplicable": req.required_when_applicable,
                        "hasDefault": req.default is not None,
                        "dependsOn": list(req.depends_on),
                        "appliesIf": req.applies_if,
                        "appliesWhen": req.applies_when,
                        "blockedIf": req.blocked_if,
                        "blockedWhen": req.blocked_when,
                    }
                    for key, req in graph._requirements.items()
                ],
            },
            "targetContracts": [
                {
                    "name": contract.name,
                    "kind": contract.kind,
                    "sourceUrl": contract.source_url,
                    "requiredDecisions": list(contract.required_decisions),
                    "requiredArtifacts": contract.required_artifacts,
                    "lineageCount": len(contract.lineage),
                }
                for contract in pattern_obj.contracts
            ],
            "samples": [
                {
                    "name": sample.name,
                    "version": sample.version,
                    "sourceUrl": sample.source_url,
                    "sourceContract": sample.source_contract,
                    "tags": sample.tags,
                }
                for sample in samples
            ],
            "policyPacks": policy_pack_inventory(pattern_obj.policy_packs),
            "targetCapabilities": [
                {
                    "key": capability.get("key", ""),
                    "type": capability.get("type", ""),
                    "handledDecisions": capability.get("handledDecisions", []),
                    "requiredDecisions": capability.get("requiredDecisions", []),
                    "producedArtifacts": capability.get("producedArtifacts", []),
                }
                for capability in target_capability_report.get("capabilities", [])
                if isinstance(capability, dict)
            ],
            "planReady": {
                "declared": pattern_obj.plan_ready,
                "expectedArtifacts": ["plan-manifest.yaml", "replay-manifest.yaml"]
                if pattern_obj.plan_ready
                else [],
            },
        },
        "runtimeContext": {
            "acceptedDecisionCount": len(decisions),
            "moduleInputCount": len(module_inputs),
            "source": payload.source_context,
            "llm": {
                "provider": extraction_summary.get("provider", "not-run"),
                "model": extraction_summary.get("model", "not-run"),
                "callCount": extraction_summary.get("callCount", 0),
                "rawEvidence": extraction_summary.get(
                    "rawEvidence",
                    {"path": "", "status": "not-run"},
                ),
            },
            "targetCapabilityPath": target_capability_report.get("selectedTargetPath", []),
            "unsupportedAskFactCount": len(
                target_capability_report.get("semanticFacts", {}).get("unsupportedAsks", [])
            ),
        },
        "outputs": {
            "expectedArtifacts": pattern_obj.expected_artifacts(),
        },
        "guardrails": [
            "Prompt context must stay bounded and reviewable.",
            "LLM output is never authoritative without graph acceptance.",
            "Target artifacts must satisfy registered contracts before handoff.",
            "Generation outside a registered target remains blocked.",
        ],
    }
    _write(output_dir, "context-manifest.yaml", data, "intent-engine/context-manifest/v1")


def gen_policy_graph(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write registered policy graph metadata when a pattern declares policy packs."""
    pattern = payload.pattern
    if not pattern:
        return

    from .patterns import GLOBAL_REGISTRY as PATTERN_REGISTRY

    pattern_obj = PATTERN_REGISTRY.get(pattern)
    if not pattern_obj.policy_packs:
        return
    data = {
        "pattern": pattern,
        "boundary": (
            "Policy graph metadata connects requirements, target contracts, artifacts, "
            "module variables, and policy-as-code references. It is not compliance "
            "attestation, deployment approval, or a deploy runner."
        ),
        "policyPacks": policy_packs_to_dict(pattern_obj.policy_packs),
    }
    _write(output_dir, "policy-graph.yaml", data, "intent-engine/policy-graph/v1")


def gen_handoff_plan(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write a generic handoff plan from pattern contracts and readiness."""
    pattern = payload.pattern
    if not pattern:
        return

    from .patterns import GLOBAL_REGISTRY as PATTERN_REGISTRY

    pattern_obj = PATTERN_REGISTRY.get(pattern)
    readiness = payload.handoff_readiness
    allowed = bool(readiness.get("handoffAllowed", True))
    allowed_next_action = readiness.get(
        "allowedNextAction",
        (
            "Resolve blockers and re-run compile before any downstream handoff."
            if not allowed
            else "Pass the reviewed artifacts to the existing target toolchain after manual gates."
        ),
    )
    target_capabilities = payload.target_capability_report
    contracts = pattern_obj.contracts
    required_artifacts = list(
        dict.fromkeys(
            artifact for contract in contracts for artifact in contract.required_artifacts
        )
    )

    review_steps = [
        {
            "id": f"review-{artifact_name.replace('/', '-').replace('.', '-').replace('_', '-')}",
            "title": f"Review {artifact_name}",
            "owner": pattern_obj.artifact_review_owners.get(artifact_name, "target-owner"),
            "dependsOn": ["validate-target-contracts"],
            "manualGate": True,
            "rollback": "Reject the handoff, correct the source intent, and re-run compile.",
        }
        for artifact_name in required_artifacts
    ]
    review_step_ids = [step["id"] for step in review_steps]
    data = {
        "pattern": pattern,
        "boundary": (
            "iac-llm-wrapper emits validated handoff artifacts only; downstream "
            "generation, execution, dashboards, and cloud changes remain outside this artifact."
        ),
        "allowedNextAction": allowed_next_action,
        "readiness": {
            "status": readiness.get("status", "ready" if allowed else "blocked"),
            "handoffAllowed": allowed,
            "blockers": readiness.get("blockers", []),
            "configReady": readiness.get("configReady", {}),
            "planReady": readiness.get("planReady", {}),
        },
        "targetContracts": [
            {
                "name": contract.name,
                "kind": contract.kind,
                "sourceUrl": contract.source_url,
                "requiredArtifacts": contract.required_artifacts,
            }
            for contract in contracts
        ],
        "steps": [
            {
                "id": "resolve-decisions",
                "title": "Confirm captured decisions and blockers",
                "owner": "architecture-owner",
                "dependsOn": [],
                "manualGate": True,
                "rollback": "Update the design document or interview answers and re-run compile.",
            },
            {
                "id": "validate-target-contracts",
                "title": "Validate required artifacts against target contracts",
                "owner": "platform-owner",
                "dependsOn": ["resolve-decisions"],
                "manualGate": True,
                "rollback": "Stop handoff until contract validation is clean.",
            },
            *review_steps,
            {
                "id": "approve-handoff",
                "title": "Approve handoff to existing provisioning toolchain",
                "owner": "release-owner",
                "dependsOn": review_step_ids or ["validate-target-contracts"],
                "manualGate": True,
                "rollback": "Keep the previous approved artifact bundle as the active handoff.",
            },
        ],
        "manualGates": [
            "No blocking gaps or contradictions remain.",
            "Target contract validation is clean.",
            "Artifact owners approve files in their domain.",
            "Rollback owner and previous known-good handoff are identified.",
            *target_capabilities.get("manualGates", []),
        ],
        "rollback": [
            "Do not mutate downstream systems from this plan.",
            "Revert to the previous approved handoff bundle in the target toolchain.",
            "Regenerate artifacts only from corrected intent.",
        ],
    }
    if target_capabilities:
        data["targetCapabilities"] = target_capabilities
    _write(output_dir, "handoff-plan.yaml", data)


def gen_replay_manifest(payload: IaCIntentPayload, output_dir: Path) -> None:
    """Write digest inventory for plan-ready registered target replay."""
    pattern = payload.pattern
    if not pattern:
        return

    from .contracts import PLAN_READY_BUNDLE_CONTRACT
    from .patterns import GLOBAL_REGISTRY as PATTERN_REGISTRY

    pattern_obj = PATTERN_REGISTRY.get(pattern)
    if not pattern_obj.plan_ready:
        return

    contracts = [*pattern_obj.contracts, PLAN_READY_BUNDLE_CONTRACT]
    files = [
        {
            "name": item.relative_to(output_dir).as_posix(),
            "sha256": replay_artifact_digest(item),
        }
        for item in _replay_artifact_paths(output_dir)
    ]
    data = {
        "pattern": pattern,
        "source": payload.source_context or {"mode": "unknown", "sha256": ""},
        "contracts": [
            {
                "name": contract.name,
                "kind": contract.kind,
                "sourceUrl": contract.source_url,
                "sha256": contract_digest(contract),
            }
            for contract in contracts
        ],
        "artifacts": {
            "files": files,
        },
        "boundary": (
            "Replay metadata pins source, contracts, and artifacts only. It does not "
            "invoke plan, apply, cloud APIs, or deployment pipelines."
        ),
    }
    _write(output_dir, "replay-manifest.yaml", data, "intent-engine/replay-manifest/v1")


def _replay_artifact_paths(output_dir: Path) -> list[Path]:
    paths: list[Path] = []
    for item in sorted(
        output_dir.rglob("*"), key=lambda path: path.relative_to(output_dir).as_posix()
    ):
        relative = item.relative_to(output_dir).as_posix()
        if relative == "replay-manifest.yaml":
            continue
        if item.is_symlink():
            raise ValueError(f"Generated replay artifact is a symlink: {relative}.")
        if item.is_dir():
            continue
        if not item.is_file():
            raise ValueError(f"Generated replay artifact is unsafe: {relative}.")
        paths.append(item)
    return paths


CORE_GENERATORS = [
    PatternGenerator(
        "context-manifest",
        gen_context_manifest,
        priority=4,
        outputs=("context-manifest.yaml",),
    ),
    PatternGenerator("policy-graph", gen_policy_graph, priority=4, outputs=("policy-graph.yaml",)),
    PatternGenerator(
        "module-inputs", gen_module_inputs, priority=5, outputs=("module-inputs.yaml",)
    ),
    PatternGenerator(
        "llm-trace-summary",
        gen_llm_trace_summary,
        priority=5,
        outputs=("llm-trace-summary.yaml",),
    ),
    PatternGenerator(
        "model-benchmark",
        gen_model_benchmark,
        priority=5,
        outputs=("model-benchmark.yaml",),
    ),
    PatternGenerator(
        "decision-audit",
        gen_decision_audit,
        priority=5,
        outputs=("decision-audit.yaml",),
    ),
    PatternGenerator(
        "sample-recommendations",
        gen_sample_recommendations,
        priority=5,
        outputs=("sample-recommendations.yaml",),
    ),
    PatternGenerator("handoff-plan", gen_handoff_plan, priority=6, outputs=("handoff-plan.yaml",)),
    PatternGenerator(
        "replay-manifest",
        gen_replay_manifest,
        priority=100,
        outputs=("replay-manifest.yaml",),
    ),
]
