"""Validation-only adapter for AWS LZA config bundles."""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from intent_engine.patterns.aws_lza.contracts import AWS_LZA_CONFIG_ARTIFACTS

from .yaml_utils import write_yaml_artifact

LZA_VALIDATION_EVIDENCE = "lza-validation-evidence.yaml"
LZA_VALIDATION_SCHEMA_VERSION = "intent-engine/aws-lza-validation-evidence/v1"
_VALIDATION_HEADER = (
    "# yaml-language-server: $schema=none\n"
    "# Generated by intent-engine — AWS LZA validation evidence, not deployment.\n"
)


class LzaValidationError(Exception):
    def __init__(self, message: str, evidence: dict[str, Any] | None = None):
        self.evidence = evidence
        super().__init__(message)


def validate_lza_config_bundle(
    *,
    bundle_dir: Path,
    lza_source: Path,
    output: Path | None = None,
) -> dict[str, Any]:
    """Run the official AWS LZA config validator against generated config files only."""
    if not bundle_dir.is_dir():
        raise LzaValidationError(f"Bundle path is not a directory: {bundle_dir}")
    missing = [name for name in AWS_LZA_CONFIG_ARTIFACTS if not (bundle_dir / name).is_file()]
    if missing:
        raise LzaValidationError(
            "Bundle is missing required AWS LZA config files: " + ", ".join(missing)
        )

    source_dir = _resolve_lza_source_dir(lza_source)
    output_path = output or bundle_dir / LZA_VALIDATION_EVIDENCE

    with tempfile.TemporaryDirectory(prefix="intent-engine-lza-config-") as temp:
        staged_config = Path(temp) / "aws-accelerator-config"
        staged_config.mkdir()
        for name in AWS_LZA_CONFIG_ARTIFACTS:
            shutil.copy2(bundle_dir / name, staged_config / name)

        command = _validator_command(staged_config)
        started = datetime.now(UTC)
        start_time = time.monotonic()
        try:
            completed = subprocess.run(
                command,
                cwd=source_dir,
                check=False,
                capture_output=True,
                text=True,
            )
            exit_code = completed.returncode
            stdout = completed.stdout
            stderr = completed.stderr
        except FileNotFoundError:
            exit_code = 127
            stdout = ""
            stderr = "yarn executable not found; install the AWS LZA development toolchain first."

        duration_ms = round((time.monotonic() - start_time) * 1000, 1)
        evidence = _build_evidence(
            bundle_dir=bundle_dir,
            lza_source=lza_source,
            source_dir=source_dir,
            staged_config=staged_config,
            command=command,
            exit_code=exit_code,
            stdout=stdout,
            stderr=stderr,
            started=started,
            duration_ms=duration_ms,
        )

    write_yaml_artifact(output_path, evidence, _VALIDATION_HEADER)
    if evidence["status"] != "pass":
        raise LzaValidationError("AWS LZA config validation failed.", evidence=evidence)
    return evidence


def _resolve_lza_source_dir(lza_source: Path) -> Path:
    if not lza_source.is_dir():
        raise LzaValidationError(f"AWS LZA source path is not a directory: {lza_source}")
    source_dir = lza_source / "source"
    if (source_dir / "package.json").is_file():
        return source_dir
    if (lza_source / "package.json").is_file():
        return lza_source
    raise LzaValidationError(
        "AWS LZA source path must be the repository root containing source/package.json "
        "or the source directory containing package.json."
    )


def _validator_command(staged_config: Path) -> list[str]:
    if shutil.which("yarn"):
        return ["yarn", "validate-config", str(staged_config)]
    if shutil.which("corepack"):
        return ["corepack", "yarn", "validate-config", str(staged_config)]
    return ["yarn", "validate-config", str(staged_config)]


def _build_evidence(
    *,
    bundle_dir: Path,
    lza_source: Path,
    source_dir: Path,
    staged_config: Path,
    command: list[str],
    exit_code: int,
    stdout: str,
    stderr: str,
    started: datetime,
    duration_ms: float,
) -> dict[str, Any]:
    return {
        "schemaVersion": LZA_VALIDATION_SCHEMA_VERSION,
        "status": "pass" if exit_code == 0 else "fail",
        "boundary": {
            "mode": "validation-only",
            "noDeploy": True,
            "noSynth": True,
            "noClone": True,
            "noInstall": True,
            "noAwsMutation": True,
            "allowedCommand": "yarn validate-config <staged-config-dir>",
            "fallbackCommand": "corepack yarn validate-config <staged-config-dir>",
        },
        "input": {
            "bundlePath": str(bundle_dir),
            "stagedConfigDir": str(staged_config),
            "configFiles": list(AWS_LZA_CONFIG_ARTIFACTS),
        },
        "lzaSource": {
            "requestedPath": str(lza_source),
            "commandWorkingDirectory": str(source_dir),
            "gitCommit": _git_commit(lza_source),
            "packageVersion": _package_version(source_dir),
        },
        "command": {
            "argv": command,
            "cwd": str(source_dir),
            "exitCode": exit_code,
            "startedAt": started.isoformat(),
            "durationMs": duration_ms,
            "stdout": stdout,
            "stderr": stderr,
        },
    }


def _git_commit(path: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(path), "rev-parse", "HEAD"],
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _package_version(source_dir: Path) -> str | None:
    package_json = source_dir / "package.json"
    if not package_json.is_file():
        return None
    try:
        data = json.loads(package_json.read_text())
    except json.JSONDecodeError:
        return None
    version = data.get("version")
    return version if isinstance(version, str) and version else None
