"""Validation-only adapter for AWS LZA config bundles."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import tempfile
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from intent_engine.patterns.aws_lza.contracts import AWS_LZA_CONFIG_ARTIFACTS

from .yaml_utils import write_yaml_artifact

LZA_VALIDATION_EVIDENCE = "lza-validation-evidence.yaml"
LZA_VALIDATION_SCHEMA_VERSION = "intent-engine/aws-lza-validation-evidence/v1"
_ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
_VALIDATION_HEADER = (
    "# yaml-language-server: $schema=none\n"
    "# Generated by intent-engine — AWS LZA validation evidence, not deployment.\n"
)


class LzaValidationError(Exception):
    def __init__(self, message: str, evidence: dict[str, Any] | None = None):
        self.evidence = evidence
        super().__init__(message)


def validate_lza_config_bundle(
    *,
    bundle_dir: Path,
    lza_source: Path,
    output: Path | None = None,
) -> dict[str, Any]:
    """Run the official AWS LZA config validator against generated config files only."""
    if not bundle_dir.is_dir():
        raise LzaValidationError(f"Bundle path is not a directory: {bundle_dir}")
    missing = [name for name in AWS_LZA_CONFIG_ARTIFACTS if not (bundle_dir / name).is_file()]
    if missing:
        raise LzaValidationError(
            "Bundle is missing required AWS LZA config files: " + ", ".join(missing)
        )

    source_dir = _resolve_lza_source_dir(lza_source)
    output_path = output or bundle_dir / LZA_VALIDATION_EVIDENCE

    with tempfile.TemporaryDirectory(prefix="intent-engine-lza-config-") as temp:
        staged_config = Path(temp) / "aws-accelerator-config"
        staged_config.mkdir()
        for name in AWS_LZA_CONFIG_ARTIFACTS:
            shutil.copy2(bundle_dir / name, staged_config / name)

        command = _validator_command(staged_config)
        started = datetime.now(UTC)
        start_time = time.monotonic()
        try:
            completed = subprocess.run(
                command,
                cwd=source_dir,
                check=False,
                capture_output=True,
                text=True,
            )
            exit_code = completed.returncode
            stdout = completed.stdout
            stderr = completed.stderr
        except FileNotFoundError:
            exit_code = 127
            stdout = ""
            stderr = (
                "yarn/corepack executable not found; install the AWS LZA development "
                "toolchain first."
            )

        duration_ms = round((time.monotonic() - start_time) * 1000, 1)
        evidence = _build_evidence(
            bundle_dir=bundle_dir,
            lza_source=lza_source,
            source_dir=source_dir,
            staged_config=staged_config,
            command=command,
            exit_code=exit_code,
            stdout=stdout,
            stderr=stderr,
            started=started,
            duration_ms=duration_ms,
        )

    write_yaml_artifact(output_path, evidence, _VALIDATION_HEADER)
    if evidence["status"] != "pass":
        raise LzaValidationError("AWS LZA config validation failed.", evidence=evidence)
    return evidence


def _resolve_lza_source_dir(lza_source: Path) -> Path:
    if not lza_source.is_dir():
        raise LzaValidationError(f"AWS LZA source path is not a directory: {lza_source}")
    source_dir = lza_source / "source"
    if (source_dir / "package.json").is_file():
        return source_dir
    if (lza_source / "package.json").is_file():
        return lza_source
    raise LzaValidationError(
        "AWS LZA source path must be the repository root containing source/package.json "
        "or the source directory containing package.json."
    )


def _validator_command(staged_config: Path) -> list[str]:
    if shutil.which("yarn"):
        return ["yarn", "validate-config", str(staged_config)]
    if shutil.which("corepack"):
        return ["corepack", "yarn", "validate-config", str(staged_config)]
    return ["yarn", "validate-config", str(staged_config)]


def _config_file_records(bundle_dir: Path) -> list[dict[str, str]]:
    return [
        {
            "name": name,
            "bundlePath": str(bundle_dir / name),
            "sha256": hashlib.sha256((bundle_dir / name).read_bytes()).hexdigest(),
        }
        for name in AWS_LZA_CONFIG_ARTIFACTS
    ]


def _build_evidence(
    *,
    bundle_dir: Path,
    lza_source: Path,
    source_dir: Path,
    staged_config: Path,
    command: list[str],
    exit_code: int,
    stdout: str,
    stderr: str,
    started: datetime,
    duration_ms: float,
) -> dict[str, Any]:
    return {
        "schemaVersion": LZA_VALIDATION_SCHEMA_VERSION,
        "status": "pass" if exit_code == 0 else "fail",
        "boundary": {
            "mode": "validation-only",
            "noDeploy": True,
            "noSynth": True,
            "noClone": True,
            "noInstall": True,
            "noAwsMutation": True,
            "allowedCommand": "yarn validate-config <staged-config-dir>",
            "fallbackCommand": "corepack yarn validate-config <staged-config-dir>",
        },
        "input": {
            "bundlePath": str(bundle_dir),
            "stagedConfigDir": str(staged_config),
            "configFiles": list(AWS_LZA_CONFIG_ARTIFACTS),
            "configFileDigests": _config_file_records(bundle_dir),
        },
        "lzaSource": {
            "requestedPath": str(lza_source),
            "commandWorkingDirectory": str(source_dir),
            "gitCommit": _git_commit(lza_source),
            "packageVersion": _package_version(source_dir),
        },
        "command": {
            "argv": command,
            "cwd": str(source_dir),
            "exitCode": exit_code,
            "startedAt": started.isoformat(),
            "durationMs": duration_ms,
            "stdout": stdout,
            "stderr": stderr,
        },
        "diagnostic": summarize_lza_validation_output(
            exit_code=exit_code,
            stdout=stdout,
            stderr=stderr,
        ),
    }


def summarize_lza_validation_output(
    *,
    exit_code: int,
    stdout: str,
    stderr: str,
) -> dict[str, str]:
    """Classify validator output without replacing the captured raw evidence."""
    lines = _clean_output_lines(stdout, stderr)
    if exit_code == 0:
        return _diagnostic(
            "passed",
            "Official AWS LZA config validator exited 0.",
            "Attach this evidence as validation output; manual owner gates still apply.",
        )

    access_denied = _first_line_containing(lines, "AccessDeniedException")
    if access_denied:
        return _diagnostic(
            "aws-account-lookup-permission",
            access_denied[access_denied.find("AccessDeniedException") :],
            (
                "Run with an AWS/LZA validation context that can perform the official "
                "account lookup, or send this failure to the downstream owner."
            ),
        )

    default_email = _first_line_containing(lines, "Default email")
    if default_email:
        return _diagnostic(
            "owner-account-email-required",
            default_email[default_email.find("Default email") :],
            "Replace generated placeholder emails with owner-approved account vending emails.",
        )

    toolchain_missing = _first_line_containing(lines, "yarn/corepack executable not found")
    if exit_code == 127 or toolchain_missing:
        return _diagnostic(
            "local-toolchain-missing",
            toolchain_missing or "yarn/corepack executable not found.",
            "Run from a prepared AWS LZA checkout with the local validation toolchain available.",
        )

    shaped_issue = _first_config_issue_line(lines)
    if shaped_issue:
        return _diagnostic(
            "schema-or-config-validation",
            shaped_issue,
            (
                "Send the exact schema/config error output to the downstream owner before "
                "claiming validation."
            ),
        )

    return _diagnostic(
        "validator-failed",
        f"Official AWS LZA config validator exited {exit_code}.",
        "Review stdout/stderr in this evidence file and resolve the concrete validator output.",
    )


def _diagnostic(category: str, summary: str, next_action: str) -> dict[str, str]:
    return {"category": category, "summary": summary, "nextAction": next_action}


def _clean_output_lines(stdout: str, stderr: str) -> list[str]:
    text = "\n".join([stdout or "", stderr or ""])
    return [_ANSI_ESCAPE_RE.sub("", line).strip() for line in text.splitlines()]


def _first_line_containing(lines: list[str], marker: str) -> str:
    for line in lines:
        if marker in line:
            return line
    return ""


def _first_config_issue_line(lines: list[str]) -> str:
    for line in lines:
        if " has " in line and " issues:" in line:
            return line.rsplit("|", 1)[-1].strip()
    for line in lines:
        if "Config file validation failed" in line:
            return "Config file validation failed."
    return ""


def _git_commit(path: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(path), "rev-parse", "HEAD"],
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _package_version(source_dir: Path) -> str | None:
    package_json = source_dir / "package.json"
    if not package_json.is_file():
        return None
    try:
        data = json.loads(package_json.read_text())
    except json.JSONDecodeError:
        return None
    version = data.get("version")
    return version if isinstance(version, str) and version else None
