"""Atmos handoff artifacts for the approved Terraform VPC target."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from intent_engine.core.replay import sha256_file
from intent_engine.core.yaml_utils import write_yaml_artifact

from .generators import map_terraform_vpc_modules
from .models import TerraformVpcIntent
from .target import (
    ROOT_FILES,
    approved_root_path,
    assert_approved_root_identity,
)

ATMOS_VERSION = "1.223.0"
ATMOS_COMPONENT = "terraform-vpc"
ATMOS_ABSTRACT_COMPONENT = "terraform-vpc/intent-defaults"
ATMOS_CATALOG_ARTIFACT = "atmos/stacks/catalog/terraform-vpc-intent.yaml"
ATMOS_COMPONENT_ROOT = "atmos/components/terraform/terraform-vpc"
ATMOS_ROOT_ARTIFACTS = tuple(f"{ATMOS_COMPONENT_ROOT}/{name}" for name in ROOT_FILES)

_HEADER = (
    "# Generated by intent-engine — abstract Atmos handoff configuration.\n"
    "# Owner stack, backend, authentication, workspace, approval, plan, and apply remain "
    "downstream.\n"
)


def gen_atmos_handoff(payload: Any, output_dir: Path) -> None:
    """Emit an importable abstract Atmos component and the exact approved root."""
    intent = getattr(payload, "intent", None)
    if not isinstance(intent, TerraformVpcIntent):
        raise TypeError(
            "Terraform VPC Atmos generator requires TerraformVpcIntent, "
            f"got {type(intent).__name__}."
        )
    assert_approved_root_identity()
    variables = dict(map_terraform_vpc_modules(intent)[0].variables)
    variables = {"region": intent.primary_region, **variables}
    catalog = {
        "components": {
            "terraform": {
                ATMOS_ABSTRACT_COMPONENT: {
                    "metadata": {
                        "type": "abstract",
                        "component": ATMOS_COMPONENT,
                        "description": (
                            "Approved Terraform VPC intent defaults. Create an owner-named real "
                            "component that inherits this abstract component."
                        ),
                    },
                    "vars": variables,
                }
            }
        }
    }
    write_yaml_artifact(output_dir / ATMOS_CATALOG_ARTIFACT, catalog, _HEADER)
    _copy_approved_root(output_dir)


def _copy_approved_root(output_dir: Path) -> None:
    source_root = approved_root_path()
    destination_root = output_dir / ATMOS_COMPONENT_ROOT
    destination_root.mkdir(parents=True, exist_ok=True)
    for name in ROOT_FILES:
        source = source_root / name
        destination = destination_root / name
        destination.write_bytes(source.read_bytes())
        if sha256_file(destination) != sha256_file(source):
            raise ValueError(f"Copied Atmos Terraform root changed: {name}.")
