# Generated by intent-engine — Terraform variables from module inputs.

# Module: lza-network
name = "lza-vpc"
cidr = "10.0.0.0/16"
hub_cidr = "10.0.0.0/20"

# Module: lza-security-baseline
audit_retention_days = 2555
block_public_access = true
