#!/usr/bin/env python3
"""Run repeatable local battle tests into ignored tests/results folders."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from io import StringIO
from pathlib import Path
from typing import Any

import ruamel.yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
EVAL_DIR = REPO_ROOT / "fixtures" / "eval"
RESULTS_DIR = REPO_ROOT / "tests" / "results"


@dataclass(frozen=True)
class BattleCase:
    name: str
    input_path: Path
    pattern: str
    expected_compile: str
    expected_artifacts: tuple[str, ...]
    expected_violations: tuple[str, ...]


def _yaml_load(path: Path) -> dict[str, Any]:
    yaml = ruamel.yaml.YAML(typ="safe")
    data = yaml.load(path.read_text())
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected mapping")
    return data


def _load_case(name: str) -> BattleCase:
    for expected_path in sorted(EVAL_DIR.glob("*.expected.yaml")):
        data = _yaml_load(expected_path)
        if data.get("name") != name:
            continue
        input_name = data.get("input")
        pattern = data.get("pattern")
        expected = data.get("expect", {})
        if not isinstance(input_name, str) or not isinstance(pattern, str):
            raise ValueError(f"{expected_path}: input and pattern must be strings")
        if not isinstance(expected, dict):
            raise ValueError(f"{expected_path}: expect must be a mapping")
        artifacts = expected.get("artifacts", [])
        violations = expected.get("violations", [])
        return BattleCase(
            name=name,
            input_path=EVAL_DIR / input_name,
            pattern=pattern,
            expected_compile=str(expected.get("compile", "pass")),
            expected_artifacts=tuple(str(item) for item in artifacts if isinstance(item, str)),
            expected_violations=tuple(str(item) for item in violations if isinstance(item, str)),
        )
    raise ValueError(f"No eval fixture named {name!r}")


def _run(cmd: list[str], *, env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=600,
    )


def _result_dir(case: BattleCase, use_llm: bool, model: str, output: Path | None) -> Path:
    if output is not None:
        return output
    mode = "llm" if use_llm else "deterministic"
    suffix = _slug(model) if use_llm and model else "auto" if use_llm else "no-llm"
    return RESULTS_DIR / f"{case.name}-{mode}-{suffix}"


def _slug(value: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in value).strip("-").lower() or "model"


def _print_proc_failure(proc: subprocess.CompletedProcess[str]) -> None:
    output = (proc.stderr or proc.stdout).strip()
    if output:
        print(output, file=sys.stderr)


def _optional_yaml(path: Path) -> dict[str, Any]:
    return _yaml_load(path) if path.exists() else {}


def _summary(output_dir: Path) -> dict[str, Any]:
    benchmark = _optional_yaml(output_dir / "model-benchmark.yaml")
    validation_path = output_dir / "contract-validation.yaml"
    validation = _optional_yaml(validation_path)
    run = benchmark.get("run", {}) if isinstance(benchmark.get("run"), dict) else {}
    latency = benchmark.get("latency", {}) if isinstance(benchmark.get("latency"), dict) else {}
    tokens = benchmark.get("tokens", {}) if isinstance(benchmark.get("tokens"), dict) else {}
    quality = benchmark.get("quality", {}) if isinstance(benchmark.get("quality"), dict) else {}
    readiness = (
        benchmark.get("readiness", {}) if isinstance(benchmark.get("readiness"), dict) else {}
    )
    validation_summary = (
        validation.get("summary", {}) if isinstance(validation.get("summary"), dict) else {}
    )
    return {
        "mode": run.get("mode", "unknown"),
        "provider": run.get("provider", "unknown"),
        "model": run.get("model", "unknown"),
        "readiness": readiness.get("status", "unknown"),
        "latencyMs": latency.get("totalMs", 0),
        "tokens": tokens.get("totalTokens", 0),
        "acceptedDecisions": quality.get("acceptedDecisionCount", 0),
        "parseErrors": quality.get("parseErrorCount", 0),
        "contractStatus": validation_summary.get("status", "unknown"),
    }


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    yaml = ruamel.yaml.YAML()
    yaml.default_flow_style = False
    yaml.indent(mapping=2, sequence=4, offset=2)
    buf = StringIO()
    yaml.dump(data, buf)
    path.write_text(
        "# yaml-language-server: $schema=none\n"
        "# Generated by intent-engine - battle-test confidence summary.\n"
        + "\n".join(line.rstrip() for line in buf.getvalue().splitlines())
        + "\n"
    )


def _git_sha() -> str:
    proc = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=30,
    )
    return proc.stdout.strip() if proc.returncode == 0 else "unknown"


def _artifact_status(output_dir: Path, expected_artifacts: tuple[str, ...]) -> list[dict[str, str]]:
    names = list(
        dict.fromkeys([*expected_artifacts, "contract-validation.yaml", "handoff-review.html"])
    )
    return [
        {
            "name": name,
            "status": "present" if (output_dir / name).exists() else "missing",
        }
        for name in names
    ]


def _finding(kind: str, area: str, message: str) -> dict[str, str]:
    return {"type": kind, "area": area, "message": message}


def _confidence_status(findings: list[dict[str, str]], area: str) -> str:
    area_findings = [item for item in findings if item["area"] == area]
    if any(item["type"] == "fail" for item in area_findings):
        return "fail"
    if any(item["type"] == "improvement" for item in area_findings):
        return "improvement"
    if any(item["type"] == "expected-weakness" for item in area_findings):
        return "expected-weakness"
    return "pass"


def _battle_summary(
    *,
    case: BattleCase,
    output_dir: Path,
    command: list[str],
    use_llm: bool,
    compile_proc: subprocess.CompletedProcess[str],
) -> dict[str, Any]:
    trace = _optional_yaml(output_dir / "llm-trace-summary.yaml")
    validation = _optional_yaml(output_dir / "contract-validation.yaml")
    handoff = _optional_yaml(output_dir / "handoff-plan.yaml")
    decision_report = _optional_yaml(output_dir / "decision-report.yaml")

    summary = _summary(output_dir)
    findings: list[dict[str, str]] = []
    compile_succeeded = compile_proc.returncode == 0
    expected_pass = case.expected_compile == "pass"
    combined_output = f"{compile_proc.stdout}\n{compile_proc.stderr}"

    if compile_succeeded != expected_pass:
        findings.append(
            _finding(
                "fail",
                "safety",
                f"Compile result mismatch: expected {case.expected_compile}, got "
                f"{'pass' if compile_succeeded else 'fail'}.",
            )
        )
    for expected_violation in case.expected_violations:
        if expected_violation not in combined_output and expected_violation not in str(
            decision_report
        ):
            findings.append(
                _finding(
                    "fail",
                    "safety",
                    f"Expected violation not surfaced: {expected_violation}.",
                )
            )

    accepted = trace.get("acceptedDecisions", {})
    raw_llm = trace.get("rawLlmDecisions", {})
    applied = trace.get("appliedDecisions", {})
    gaps = trace.get("gaps", {})
    contradictions = trace.get("contradictions", {})
    if not isinstance(accepted, dict) or not accepted:
        findings.append(_finding("fail", "extraction", "No accepted decisions captured."))
    if case.pattern == "aws-lza" and isinstance(accepted, dict):
        required_keys = {
            "network_account",
            "identity_center_permission_sets",
            "identity_center_assignments",
        }
        missing = sorted(key for key in required_keys if key not in accepted)
        if missing and expected_pass:
            findings.append(
                _finding(
                    "fail",
                    "extraction",
                    f"Required enterprise decisions missing: {', '.join(missing)}.",
                )
            )
    if isinstance(raw_llm, dict):
        invented = sorted(set(raw_llm) - set(accepted)) if isinstance(accepted, dict) else []
        if invented:
            findings.append(
                _finding(
                    "improvement",
                    "extraction",
                    f"Raw LLM decisions were not accepted by graph: {', '.join(invented)}.",
                )
            )
    if isinstance(applied, dict):
        markdown_applied = applied.get("markdown", [])
        llm_applied = applied.get("llm", [])
        if markdown_applied and not llm_applied and use_llm:
            findings.append(
                _finding(
                    "expected-weakness",
                    "model",
                    "Structured Markdown carried the handoff; LLM added no accepted decisions.",
                )
            )
    if isinstance(gaps, dict):
        raw_gaps = gaps.get("raw", [])
        blocking_gaps = gaps.get("blocking", [])
        if isinstance(raw_gaps, list) and isinstance(blocking_gaps, list):
            if len(blocking_gaps) > len(raw_gaps):
                findings.append(
                    _finding("fail", "extraction", "Blocking gaps exceed raw LLM gaps.")
                )
    if isinstance(contradictions, dict):
        blocking_contradictions = contradictions.get("blocking", [])
        if blocking_contradictions and expected_pass:
            findings.append(
                _finding(
                    "fail",
                    "safety",
                    "Blocking contradictions surfaced in an expected-pass battle.",
                )
            )

    artifact_status = _artifact_status(output_dir, case.expected_artifacts)
    missing_artifacts = [item["name"] for item in artifact_status if item["status"] != "present"]
    if missing_artifacts and expected_pass:
        findings.append(
            _finding(
                "fail",
                "handoff",
                f"Expected artifacts missing: {', '.join(missing_artifacts)}.",
            )
        )
    validation_summary = validation.get("summary", {})
    if expected_pass and (
        not isinstance(validation_summary, dict) or validation_summary.get("status") != "pass"
    ):
        findings.append(_finding("fail", "handoff", "Contract validation did not pass."))
    allowed_next_action = handoff.get("allowedNextAction")
    if expected_pass and not allowed_next_action:
        findings.append(_finding("fail", "handoff", "handoff-plan.yaml has no allowedNextAction."))
    review_path = output_dir / "handoff-review.html"
    if expected_pass and not review_path.exists():
        findings.append(_finding("fail", "handoff", "Review page was not generated."))
    elif review_path.exists():
        review_text = review_path.read_text()
        for marker in ("Readiness", "Contract Validation", "Model Benchmark"):
            if marker not in review_text:
                findings.append(
                    _finding("fail", "handoff", f"Review page missing section: {marker}.")
                )

    for forbidden in ("terraform.tfvars", "main.tf", "terragrunt.hcl"):
        if (output_dir / forbidden).exists() and case.pattern == "aws-lza":
            findings.append(
                _finding("fail", "safety", f"Unexpected deployable scaffold emitted: {forbidden}.")
            )
    if use_llm and not (output_dir / "raw-evidence.yaml").exists():
        findings.append(_finding("fail", "safety", "Raw LLM evidence was not preserved."))

    if use_llm:
        if summary["latencyMs"] in (0, "0", None):
            findings.append(_finding("fail", "model", "Latency was not captured."))
        if summary["parseErrors"]:
            findings.append(_finding("fail", "model", "LLM parse errors were captured."))
        if summary["tokens"] in (0, "0", None):
            findings.append(
                _finding(
                    "expected-weakness",
                    "model",
                    "Provider did not report token usage.",
                )
            )
    if not (output_dir / "model-benchmark.yaml").exists():
        findings.append(_finding("fail", "model", "model-benchmark.yaml missing."))

    confidence = {
        "extraction": _confidence_status(findings, "extraction"),
        "handoff": _confidence_status(findings, "handoff"),
        "safety": _confidence_status(findings, "safety"),
        "model": _confidence_status(findings, "model"),
        "regression": "pass" if not any(item["type"] == "fail" for item in findings) else "fail",
    }
    verdict = "fail" if confidence["regression"] == "fail" else "pass"
    return {
        "schemaVersion": "intent-engine/battle-summary/v1",
        "verdict": verdict,
        "meaning": "confidence increased" if verdict == "pass" else "bug or weakness found",
        "fixture": case.name,
        "pattern": case.pattern,
        "input": str(case.input_path.relative_to(REPO_ROOT)),
        "expectedCompile": case.expected_compile,
        "actualCompile": "pass" if compile_succeeded else "fail",
        "generatedAt": datetime.now(UTC).isoformat(),
        "gitCommit": _git_sha(),
        "command": " ".join(command),
        "output": {
            "directory": str(output_dir),
            "reviewPage": str(output_dir / "handoff-review.html"),
            "battleSummary": str(output_dir / "battle-summary.yaml"),
        },
        "confidence": confidence,
        "metrics": summary,
        "artifacts": artifact_status,
        "findings": findings,
        "improvementItems": [
            dict(item) for item in findings if item["type"] in {"improvement", "expected-weakness"}
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture",
        default="aws-lza-complex-enterprise-handoff",
        help="Eval fixture case name",
    )
    parser.add_argument("--llm", action="store_true", help="Use configured LLM")
    parser.add_argument("--provider", default="", help="LLM provider for --llm")
    parser.add_argument("--model", default="", help="LLM model for --llm")
    parser.add_argument("--output", type=Path, help="Output directory")
    parser.add_argument(
        "--keep",
        action="store_true",
        help="Keep existing output directory contents instead of replacing them",
    )
    args = parser.parse_args()

    case = _load_case(args.fixture)
    output_dir = _result_dir(case, args.llm, args.model, args.output).resolve()
    if output_dir.exists() and not args.keep:
        if RESULTS_DIR not in output_dir.parents:
            raise RuntimeError(f"Refusing to delete non-results directory: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    if not args.llm:
        env["INTENT_ENGINE_DISABLE_LLM"] = "1"
    else:
        env.pop("INTENT_ENGINE_DISABLE_LLM", None)

    compile_cmd = [
        sys.executable,
        "-m",
        "intent_engine",
        "compile",
        "--input",
        str(case.input_path),
        "--output",
        str(output_dir),
        "--pattern",
        case.pattern,
    ]
    if args.provider:
        compile_cmd.extend(["--provider", args.provider])
    if args.model:
        compile_cmd.extend(["--model", args.model])
    if args.llm:
        compile_cmd.extend(["--evidence-output", str(output_dir / "raw-evidence.yaml")])

    compile_proc = _run(compile_cmd, env=env)
    if compile_proc.returncode != 0 and case.expected_compile != "fail":
        _print_proc_failure(compile_proc)
        return compile_proc.returncode

    review_proc = _run(
        [
            sys.executable,
            "-m",
            "intent_engine",
            "review",
            "html",
            "--input",
            str(output_dir),
            "--output",
            str(output_dir / "handoff-review.html"),
        ],
        env=env,
    )
    if review_proc.returncode != 0:
        _print_proc_failure(review_proc)
        return review_proc.returncode

    battle_summary = _battle_summary(
        case=case,
        output_dir=output_dir,
        command=[Path(sys.executable).name, *sys.argv],
        use_llm=args.llm,
        compile_proc=compile_proc,
    )
    _write_yaml(output_dir / "battle-summary.yaml", battle_summary)
    summary = _summary(output_dir)
    print(f"Output: {output_dir}")
    print(f"Review page: {output_dir / 'handoff-review.html'}")
    print(f"Battle summary: {output_dir / 'battle-summary.yaml'}")
    print(
        "Summary: "
        f"verdict={battle_summary['verdict']} "
        f"mode={summary['mode']} "
        f"provider={summary['provider']} "
        f"model={summary['model']} "
        f"readiness={summary['readiness']} "
        f"latencyMs={summary['latencyMs']} "
        f"tokens={summary['tokens']} "
        f"acceptedDecisions={summary['acceptedDecisions']} "
        f"parseErrors={summary['parseErrors']} "
        f"contractStatus={summary['contractStatus']}"
    )
    return 0 if battle_summary["verdict"] == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
