"""AWS LZA thin-path pattern.

This pattern turns architecture intent into validated AWS Landing Zone
Accelerator handoff artifacts. It deliberately emits LZA configuration
inputs and runbook context instead of generating a parallel IaC stack.
"""

from __future__ import annotations

from io import StringIO
from pathlib import Path
from typing import Any

import ruamel.yaml

from intent_engine.core.contracts import ContractValidator
from intent_engine.core.generator import register_generator
from intent_engine.core.patterns import GLOBAL_REGISTRY, Pattern
from intent_engine.core.requirements import Requirement, RequirementGraph
from intent_engine.core.sample_config import GLOBAL_SAMPLE_REGISTRY, SampleConfig
from intent_engine.core.validator import Violation

from .contracts import AWS_LZA_SAMPLE_CONFIG_CONTRACT
from .models import AwsLzaIntent

_LZA_CONTRACT = AWS_LZA_SAMPLE_CONFIG_CONTRACT
_SECURITY_OU = "Security"
_INFRASTRUCTURE_OU = "Infrastructure"
_WORKLOADS_OU = "Workloads"
_MANAGEMENT_ACCOUNT = "Management"
_PLACEHOLDER_EMAIL_DOMAIN = "example.com"
_AWS_LZA_SAMPLE_RELEASE_DATE = "2026-05-27"


def _yaml_dump(data: Any) -> str:
    yaml = ruamel.yaml.YAML()
    yaml.default_flow_style = False
    yaml.indent(mapping=2, sequence=4, offset=2)
    buf = StringIO()
    yaml.dump(data, buf)
    return buf.getvalue()


def _write_yaml(output_dir: Path, name: str, data: Any) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    header = (
        "# yaml-language-server: $schema=none\n"
        "# Generated by intent-engine — AWS LZA handoff artifact.\n"
    )
    (output_dir / name).write_text(header + _yaml_dump(data))


def _aws_lza_intent(payload: Any) -> AwsLzaIntent | None:
    intent = getattr(payload, "intent", payload)
    if isinstance(intent, AwsLzaIntent):
        return intent
    return None


def _normalized_ous(intent: AwsLzaIntent) -> set[str]:
    return {ou.strip().lower() for ou in intent.organizational_units if ou.strip()}


def _management_access_role(intent: AwsLzaIntent) -> str:
    if str(intent.org_mode) == "control-tower":
        return "AWSControlTowerExecution"
    return "OrganizationAccountAccessRole"


def _slug(value: str) -> str:
    return "".join(char.lower() for char in value if char.isalnum()) or "account"


def _placeholder_email(account_name: str) -> str:
    return f"{_slug(account_name)}@{_PLACEHOLDER_EMAIL_DOMAIN}"


def _account_record(name: str, organizational_unit: str | None = None) -> dict[str, str]:
    account = {"name": name, "email": _placeholder_email(name)}
    if organizational_unit:
        account["organizationalUnit"] = organizational_unit
    return account


def _primary_vpc_account(intent: AwsLzaIntent) -> str:
    if intent.topology == "hub-spoke":
        return intent.network_account
    if intent.workload_accounts:
        return intent.workload_accounts[0]
    return intent.security_tooling_account


def _mandatory_accounts(intent: AwsLzaIntent) -> list[dict[str, str]]:
    return [
        _account_record(_MANAGEMENT_ACCOUNT),
        _account_record(intent.log_archive_account, _SECURITY_OU),
        _account_record(intent.audit_account, _SECURITY_OU),
    ]


def _workload_accounts(intent: AwsLzaIntent) -> list[dict[str, str]]:
    accounts = [_account_record(intent.security_tooling_account, _SECURITY_OU)]
    if intent.topology == "hub-spoke":
        accounts.append(_account_record(intent.network_account, _INFRASTRUCTURE_OU))
    accounts.extend(_account_record(name, _WORKLOADS_OU) for name in intent.workload_accounts)
    return accounts


def _security_hub_standards(intent: AwsLzaIntent) -> list[dict[str, Any]]:
    standards = [{"name": "AWS Foundational Security Best Practices v1.0.0", "enable": True}]
    overlay = str(intent.compliance_overlay)
    if overlay == "regulated":
        standards.append({"name": "NIST Special Publication 800-53 Revision 5", "enable": True})
    elif overlay == "financial-services":
        standards.append({"name": "PCI DSS v4.0.1", "enable": True})
    elif overlay == "healthcare":
        standards.append({"name": "NIST Special Publication 800-53 Revision 5", "enable": True})
    return standards


def _identity_center_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "name": f"{intent.organization_name} Identity Center",
        "delegatedAdminAccount": intent.identity_center_delegated_admin_account,
        "identityCenterPermissionSets": [],
        "identityCenterAssignments": [],
    }


def _guardduty_export_configuration(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "enable": intent.centralized_logging,
        "destinationType": "S3",
        "exportFrequency": "ONE_HOUR",
    }


def _guardduty_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "enable": intent.guardduty_enabled,
        "autoEnableOrgMembers": True,
        "excludeRegions": [],
        "s3Protection": {"enable": intent.centralized_logging},
        "exportConfiguration": _guardduty_export_configuration(intent),
    }


def _security_hub_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "enable": intent.security_hub_enabled,
        "autoEnableOrgMembers": True,
        "regionAggregation": True,
        "standards": _security_hub_standards(intent),
    }


def _core_vpc_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "name": "Core",
        "account": _primary_vpc_account(intent),
        "region": intent.home_region,
        "cidrs": [intent.network_cidr],
        "enableDnsHostnames": True,
        "enableDnsSupport": True,
        "routeTables": [],
        "subnets": [],
        "transitGatewayAttachments": [],
    }


def _aws_lza_graph_factory() -> RequirementGraph:
    graph = RequirementGraph()
    graph.add(
        Requirement(
            key="baseline",
            target_field="baseline",
            target_type="LzaBaseline",
            label="LZA Baseline",
            question="Which AWS LZA sample configuration baseline should be used?",
            options=["standard", "universal", "healthcare", "education", "govcloud"],
            default="standard",
            category="accelerator",
            hint=(
                "Start from AWS-maintained sample configurations, then override only what differs."
            ),
        )
    )
    graph.add(
        Requirement(
            key="org_mode",
            target_field="org_mode",
            target_type="LzaOrgMode",
            label="Organization Mode",
            question="Should this landing zone use Control Tower or raw AWS Organizations?",
            options=["control-tower", "raw-orgs"],
            default="control-tower",
            category="organization",
            hint="AWS recommends Control Tower first for greenfield commercial landing zones.",
        )
    )
    graph.add(
        Requirement(
            key="organization_name",
            target_field="organization_name",
            target_type="string",
            label="Organization Name",
            question="What organization name should be used in the LZA handoff?",
            default="ExampleCorp",
            category="organization",
        )
    )
    graph.add(
        Requirement(
            key="home_region",
            target_field="home_region",
            target_type="string",
            label="Home Region",
            question="Which AWS region is the home region?",
            default="eu-central-1",
            category="organization",
        )
    )
    graph.add(
        Requirement(
            key="enabled_regions",
            target_field="enabled_regions",
            target_type="string_list",
            label="Enabled Regions",
            question="Which AWS regions should LZA enable? Use comma-separated values.",
            default="eu-central-1",
            category="organization",
        )
    )
    graph.add(
        Requirement(
            key="organizational_units",
            target_field="organizational_units",
            target_type="string_list",
            label="Organizational Units",
            question="Which OUs are required? Use comma-separated values.",
            default="Security, Infrastructure, Workloads",
            category="organization",
        )
    )
    graph.add(
        Requirement(
            key="workload_accounts",
            target_field="workload_accounts",
            target_type="string_list",
            label="Workload Accounts",
            question="Which workload accounts should be included? Use comma-separated values.",
            default="Prod",
            category="accounts",
        )
    )
    graph.add(
        Requirement(
            key="audit_account",
            target_field="audit_account",
            target_type="string",
            label="Audit Account",
            question="Which account owns audit and security audit functions?",
            default="Audit",
            category="accounts",
        )
    )
    graph.add(
        Requirement(
            key="log_archive_account",
            target_field="log_archive_account",
            target_type="string",
            label="Log Archive Account",
            question="Which account stores immutable centralized logs?",
            default="LogArchive",
            category="accounts",
        )
    )
    graph.add(
        Requirement(
            key="security_tooling_account",
            target_field="security_tooling_account",
            target_type="string",
            label="Security Tooling Account",
            question="Which account owns delegated security tooling administration?",
            default="SecurityTooling",
            category="accounts",
        )
    )
    graph.add(
        Requirement(
            key="network_account",
            target_field="network_account",
            target_type="string",
            label="Network Account",
            question="Which account owns shared networking?",
            default="Network",
            category="network",
            applies_if={"topology": ["hub-spoke"]},
            violation_code="AWS_LZA_NETWORK_ACCOUNT_REQUIRED",
            violation_message="Hub-spoke topology requires a network account.",
        )
    )
    graph.add(
        Requirement(
            key="identity_center_delegated_admin_account",
            target_field="identity_center_delegated_admin_account",
            target_type="string",
            label="Identity Center Delegated Admin",
            question="Which account is delegated administrator for IAM Identity Center?",
            default="SecurityTooling",
            category="identity",
        )
    )
    graph.add(
        Requirement(
            key="topology",
            target_field="topology",
            target_type="LzaTopology",
            label="Network Topology",
            question="Which network topology should LZA configure?",
            options=["single-vpc", "hub-spoke"],
            default="hub-spoke",
            category="network",
        )
    )
    graph.add(
        Requirement(
            key="network_cidr",
            target_field="network_cidr",
            target_type="string",
            label="Network CIDR",
            question="What private CIDR should the landing zone reserve for networking?",
            default="10.0.0.0/16",
            category="network",
        )
    )
    graph.add(
        Requirement(
            key="centralized_logging",
            target_field="centralized_logging",
            target_type="bool",
            label="Centralized Logging",
            question="Should centralized logging be enabled?",
            options=["true", "false"],
            default="true",
            category="security",
        )
    )
    graph.add(
        Requirement(
            key="security_hub_enabled",
            target_field="security_hub_enabled",
            target_type="bool",
            label="Security Hub",
            question="Should AWS Security Hub be enabled by the LZA baseline?",
            options=["true", "false"],
            default="true",
            category="security",
        )
    )
    graph.add(
        Requirement(
            key="guardduty_enabled",
            target_field="guardduty_enabled",
            target_type="bool",
            label="GuardDuty",
            question="Should GuardDuty be enabled by the LZA baseline?",
            options=["true", "false"],
            default="true",
            category="security",
        )
    )
    graph.add(
        Requirement(
            key="compliance_overlay",
            target_field="compliance_overlay",
            target_type="ComplianceOverlay",
            label="Compliance Overlay",
            question="Which compliance overlay applies?",
            options=["none", "regulated", "financial-services", "healthcare", "education"],
            default="none",
            category="security",
            hint="Overlay selects extra decisions; it does not replace AWS/customer attestation.",
        )
    )
    return graph


def validate_aws_lza_intent(intent: AwsLzaIntent, graph=None) -> list[Violation]:
    violations: list[Violation] = ContractValidator(_LZA_CONTRACT).validate_intent(intent)
    ous = _normalized_ous(intent)
    if _SECURITY_OU.lower() not in ous:
        violations.append(
            Violation(
                code="AWS_LZA_SECURITY_OU_REQUIRED",
                message="AWS LZA baseline requires a Security OU for audit and log accounts.",
            )
        )
    if intent.topology == "hub-spoke" and _INFRASTRUCTURE_OU.lower() not in ous:
        violations.append(
            Violation(
                code="AWS_LZA_INFRASTRUCTURE_OU_REQUIRED",
                message="Hub-spoke topology requires an Infrastructure OU for the network account.",
            )
        )
    if intent.workload_accounts and _WORKLOADS_OU.lower() not in ous:
        violations.append(
            Violation(
                code="AWS_LZA_WORKLOADS_OU_REQUIRED",
                message="Workload accounts require a Workloads OU in organization-config.yaml.",
            )
        )
    if intent.centralized_logging and not intent.log_archive_account.strip():
        violations.append(
            Violation(
                code="AWS_LZA_LOG_ARCHIVE_ACCOUNT_REQUIRED",
                message="Centralized logging requires a log archive account.",
            )
        )
    if intent.centralized_logging and not intent.audit_account.strip():
        violations.append(
            Violation(
                code="AWS_LZA_AUDIT_ACCOUNT_REQUIRED",
                message="Centralized logging requires an audit account.",
            )
        )
    if not intent.security_tooling_account.strip():
        violations.append(
            Violation(
                code="AWS_LZA_SECURITY_TOOLING_ACCOUNT_REQUIRED",
                message="AWS LZA handoff requires a security tooling account.",
            )
        )
    all_accounts = {
        intent.audit_account,
        intent.log_archive_account,
        intent.security_tooling_account,
        intent.network_account,
        *intent.workload_accounts,
    }
    if intent.identity_center_delegated_admin_account not in all_accounts:
        violations.append(
            Violation(
                code="AWS_LZA_IDENTITY_CENTER_ADMIN_UNKNOWN",
                message="Identity Center delegated administrator must reference a known account.",
            )
        )
    if intent.topology == "hub-spoke" and not intent.network_account.strip():
        violations.append(
            Violation(
                code="AWS_LZA_NETWORK_ACCOUNT_REQUIRED",
                message="Hub-spoke topology requires a network account.",
            )
        )
    if intent.home_region not in intent.enabled_regions:
        violations.append(
            Violation(
                code="AWS_LZA_HOME_REGION_NOT_ENABLED",
                message="Home region must be present in enabled regions.",
            )
        )
    return violations


def gen_lza_organization_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "enable": True,
        "organizationalUnits": [{"name": name} for name in intent.organizational_units],
        "serviceControlPolicies": [],
        "taggingPolicies": [],
        "backupPolicies": [],
    }
    _write_yaml(output_dir, "organization-config.yaml", data)


def gen_lza_accounts_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    _write_yaml(
        output_dir,
        "accounts-config.yaml",
        {
            "mandatoryAccounts": _mandatory_accounts(intent),
            "workloadAccounts": _workload_accounts(intent),
        },
    )


def gen_lza_global_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "homeRegion": intent.home_region,
        "enabledRegions": intent.enabled_regions,
        "managementAccountAccessRole": _management_access_role(intent),
        "cloudwatchLogRetentionInDays": 2555,
        "controlTower": {"enable": str(intent.org_mode) == "control-tower"},
        "logging": {
            "account": intent.log_archive_account,
            "cloudtrail": {
                "enable": intent.centralized_logging,
                "organizationTrail": intent.centralized_logging,
            },
            "sessionManager": {
                "sendToCloudWatchLogs": intent.centralized_logging,
                "sendToS3": intent.centralized_logging,
            },
        },
    }
    _write_yaml(output_dir, "global-config.yaml", data)


def gen_lza_security_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "homeRegion": intent.home_region,
        "accessAnalyzer": {"enable": True},
        "iamPasswordPolicy": {
            "allowUsersToChangePassword": True,
            "hardExpiry": False,
            "requireUppercaseCharacters": True,
            "requireLowercaseCharacters": True,
            "requireSymbols": True,
            "requireNumbers": True,
            "minimumPasswordLength": 14,
            "passwordReusePrevention": 24,
            "maxPasswordAge": 90,
        },
        "awsConfig": {"enableConfigurationRecorder": True},
        "cloudWatch": {
            "metricSets": [],
            "alarmSets": [],
        },
        "centralSecurityServices": {
            "delegatedAdminAccount": intent.security_tooling_account,
            "ebsDefaultVolumeEncryption": {"enable": True},
            "s3PublicAccessBlock": {"enable": True},
            "macie": {
                "enable": str(intent.compliance_overlay) != "none",
                "publishSensitiveDataFindings": str(intent.compliance_overlay)
                in {"regulated", "financial-services", "healthcare"},
            },
            "guardduty": _guardduty_config(intent),
            "securityHub": _security_hub_config(intent),
            "ssmAutomation": {"documentSets": []},
        },
    }
    _write_yaml(output_dir, "security-config.yaml", data)


def gen_lza_iam_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "homeRegion": intent.home_region,
        "identityCenter": _identity_center_config(intent),
    }
    _write_yaml(output_dir, "iam-config.yaml", data)


def gen_lza_network_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "defaultVpc": {"delete": True},
        "endpointPolicies": [],
        "transitGateways": [],
        "vpcs": [_core_vpc_config(intent)],
    }
    if intent.topology == "hub-spoke":
        data["centralNetworkServices"] = {"delegatedAdminAccount": intent.network_account}
        data["transitGateways"] = [
            {
                "name": "Core",
                "account": intent.network_account,
                "region": intent.home_region,
                "asn": 64512,
                "dnsSupport": "enable",
                "vpnEcmpSupport": "enable",
                "defaultRouteTableAssociation": "disable",
                "defaultRouteTablePropagation": "disable",
                "autoAcceptSharingAttachments": "enable",
                "routeTables": [{"name": "Core", "routes": []}],
            }
        ]
    _write_yaml(output_dir, "network-config.yaml", data)


def gen_lza_lineage_manifest(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "sourceContract": {
            "name": _LZA_CONTRACT.name,
            "kind": _LZA_CONTRACT.kind,
            "url": _LZA_CONTRACT.source_url,
            "baseline": str(intent.baseline),
            "mandatoryConfigFiles": _LZA_CONTRACT.required_artifacts,
            "optionalConfigFiles": _LZA_CONTRACT.optional_artifacts,
        },
        "artifacts": [artifact.model_dump(by_alias=True) for artifact in _LZA_CONTRACT.artifacts],
        "lineage": [item.model_dump() for item in _LZA_CONTRACT.lineage],
    }
    _write_yaml(output_dir, "lineage-manifest.yaml", data)


def gen_lza_deployment_runbook(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    output_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AWS LZA Deployment Runbook",
        "",
        "## Inputs",
        "",
        f"- Baseline: `{intent.baseline}`",
        f"- Organization mode: `{intent.org_mode}`",
        f"- Home region: `{intent.home_region}`",
        f"- Enabled regions: `{', '.join(intent.enabled_regions)}`",
        "",
        "## LZA Config Contract",
        "",
        "Mandatory configuration files:",
        "",
        *[f"- `{name}`" for name in _LZA_CONTRACT.required_artifacts],
        "",
        "Optional configuration files are emitted only when custom target contracts require them:",
        "",
        *[f"- `{name}`" for name in _LZA_CONTRACT.optional_artifacts],
        "",
        "## Sequence",
        "",
        "1. Confirm AWS Organizations or Control Tower baseline matches `org_mode`.",
        "2. Review generated LZA configuration files and compare with AWS sample baseline.",
        "3. Replace placeholder account emails before deployment.",
        (
            "4. Populate customer-specific Identity Center assignments, VPC route "
            "tables/subnets, and optional security exports."
        ),
        "5. Run AWS LZA deployment using its documented installer and pipeline.",
        (
            "6. Preserve `decision-report.yaml`, `decision-audit.yaml`, and "
            "`lineage-manifest.yaml` as handoff evidence."
        ),
        "",
        "## Boundary",
        "",
        "This handoff does not generate a parallel Terraform or Terragrunt landing-zone stack.",
        "Use AWS LZA for landing-zone deployment unless a documented gap requires custom IaC.",
    ]
    (output_dir / "deployment-runbook.md").write_text("\n".join(lines) + "\n")


def gen_lza_decision_report(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    if intent is None:
        return
    data = {
        "pattern": "aws-lza",
        "baseline": str(intent.baseline),
        "orgMode": str(intent.org_mode),
        "organizationName": intent.organization_name,
        "homeRegion": intent.home_region,
        "enabledRegions": intent.enabled_regions,
        "organizationalUnits": intent.organizational_units,
        "accounts": {
            "audit": intent.audit_account,
            "logArchive": intent.log_archive_account,
            "securityTooling": intent.security_tooling_account,
            "network": intent.network_account,
            "workloads": intent.workload_accounts,
        },
        "identity": {
            "identityCenterDelegatedAdmin": intent.identity_center_delegated_admin_account,
        },
        "network": {
            "topology": str(intent.topology),
            "cidr": intent.network_cidr,
        },
        "security": {
            "centralizedLogging": intent.centralized_logging,
            "securityHubEnabled": intent.security_hub_enabled,
            "guardDutyEnabled": intent.guardduty_enabled,
            "complianceOverlay": str(intent.compliance_overlay),
        },
    }
    _write_yaml(output_dir, "decision-report.yaml", data)


_AWS_LZA_SECTION_MAP: dict[str, tuple[str, str | None]] = {
    "baseline": ("LZA Baseline", "baseline"),
    "org_mode": ("Organization", "org_mode"),
    "organization_name": ("Organization", "organization_name"),
    "home_region": ("Regions", "home_region"),
    "enabled_regions": ("Regions", "enabled_regions"),
    "organizational_units": ("Organization", "organizational_units"),
    "workload_accounts": ("Accounts", "workload_accounts"),
    "audit_account": ("Accounts", "audit_account"),
    "log_archive_account": ("Accounts", "log_archive_account"),
    "security_tooling_account": ("Accounts", "security_tooling_account"),
    "network_account": ("Accounts", "network_account"),
    "identity_center_delegated_admin_account": (
        "Identity",
        "identity_center_delegated_admin_account",
    ),
    "topology": ("Network", "topology"),
    "network_cidr": ("Network", "network_cidr"),
    "centralized_logging": ("Security", "centralized_logging"),
    "security_hub_enabled": ("Security", "security_hub_enabled"),
    "guardduty_enabled": ("Security", "guardduty_enabled"),
    "compliance_overlay": ("Security", "compliance_overlay"),
}

_AWS_LZA_SECTION_ORDER = [
    "LZA Baseline",
    "Organization",
    "Regions",
    "Accounts",
    "Identity",
    "Network",
    "Security",
]

_AWS_LZA_FREE_FORM_EXAMPLES = {
    "Regions": ["enabled_regions: eu-central-1, eu-west-1"],
    "Accounts": ["workload_accounts: Dev, Test, Prod"],
}


def _register_aws_lza_sample(
    *,
    name: str,
    description: str,
    upstream_variant: str,
    tags: list[str],
    decisions: dict[str, Any],
) -> None:
    GLOBAL_SAMPLE_REGISTRY.register(
        SampleConfig(
            name=name,
            pattern="aws-lza",
            description=description,
            version="1.0.0",
            release_date=_AWS_LZA_SAMPLE_RELEASE_DATE,
            source_url=_LZA_CONTRACT.source_url,
            source_contract=_LZA_CONTRACT.name,
            upstream_variant=upstream_variant,
            tags=tags,
            decisions=decisions,
        )
    )


_AWS_LZA_GENERATOR_SCOPE = {"aws-lza"}

register_generator(
    "aws-lza-organization",
    gen_lza_organization_config,
    priority=20,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-accounts",
    gen_lza_accounts_config,
    priority=21,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-global",
    gen_lza_global_config,
    priority=22,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-security",
    gen_lza_security_config,
    priority=23,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-iam",
    gen_lza_iam_config,
    priority=24,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-network",
    gen_lza_network_config,
    priority=25,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-decision-report",
    gen_lza_decision_report,
    priority=26,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-lineage",
    gen_lza_lineage_manifest,
    priority=27,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)
register_generator(
    "aws-lza-runbook",
    gen_lza_deployment_runbook,
    priority=28,
    applies_to=_AWS_LZA_GENERATOR_SCOPE,
)

GLOBAL_REGISTRY.register(
    Pattern(
        name="aws-lza",
        description="Thin AWS Landing Zone Accelerator handoff path",
        graph_factory=_aws_lza_graph_factory,
        intent_factory=AwsLzaIntent,
        validators=[validate_aws_lza_intent],
        section_map=dict(_AWS_LZA_SECTION_MAP),
        section_order=list(_AWS_LZA_SECTION_ORDER),
        free_form_examples=dict(_AWS_LZA_FREE_FORM_EXAMPLES),
        prompt_context=(
            "This pattern gathers decisions for AWS Landing Zone Accelerator. "
            "Use AWS LZA sample configurations as the downstream deployment contract. "
            "Extract only decisions needed for LZA configuration and handoff; do not infer "
            "custom Terraform unless explicitly requested."
        ),
        extra_artifacts=[
            "decision-report.yaml",
            "lineage-manifest.yaml",
            "deployment-runbook.md",
        ],
        contracts=[_LZA_CONTRACT],
    )
)

_register_aws_lza_sample(
    name="aws-lza-standard-v1",
    description="Commercial Control Tower baseline with hub-spoke networking and central logging.",
    upstream_variant="standard",
    tags=["aws-lza", "standard", "control-tower", "hub-spoke"],
    decisions={
        "baseline": "standard",
        "org_mode": "control-tower",
        "home_region": "eu-central-1",
        "enabled_regions": ["eu-central-1"],
        "organizational_units": ["Security", "Infrastructure", "Workloads"],
        "workload_accounts": ["Prod"],
        "security_tooling_account": "SecurityTooling",
        "identity_center_delegated_admin_account": "SecurityTooling",
        "topology": "hub-spoke",
        "centralized_logging": "true",
        "security_hub_enabled": "true",
        "guardduty_enabled": "true",
    },
)

_register_aws_lza_sample(
    name="aws-lza-regulated-v1",
    description="Standard AWS LZA baseline plus regulated-industry security overlay.",
    upstream_variant="standard",
    tags=["aws-lza", "regulated", "security-hub", "nist"],
    decisions={
        "baseline": "standard",
        "org_mode": "control-tower",
        "home_region": "eu-central-1",
        "enabled_regions": ["eu-central-1", "eu-west-1"],
        "organizational_units": ["Security", "Infrastructure", "Workloads"],
        "workload_accounts": ["Prod"],
        "security_tooling_account": "SecurityTooling",
        "identity_center_delegated_admin_account": "SecurityTooling",
        "topology": "hub-spoke",
        "centralized_logging": "true",
        "security_hub_enabled": "true",
        "guardduty_enabled": "true",
        "compliance_overlay": "regulated",
    },
)

_register_aws_lza_sample(
    name="aws-lza-healthcare-v1",
    description="Healthcare AWS LZA sample path with healthcare baseline and PHI-focused overlay.",
    upstream_variant="healthcare",
    tags=["aws-lza", "healthcare", "hipaa", "phi"],
    decisions={
        "baseline": "healthcare",
        "org_mode": "control-tower",
        "home_region": "eu-central-1",
        "enabled_regions": ["eu-central-1"],
        "organizational_units": ["Security", "Infrastructure", "Workloads"],
        "workload_accounts": ["ClinicalProd"],
        "security_tooling_account": "SecurityTooling",
        "identity_center_delegated_admin_account": "SecurityTooling",
        "topology": "hub-spoke",
        "centralized_logging": "true",
        "security_hub_enabled": "true",
        "guardduty_enabled": "true",
        "compliance_overlay": "healthcare",
    },
)
