"""AWS LZA artifact generators."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from intent_engine.core.yaml_utils import write_yaml_artifact

from .contracts import AWS_LZA_CONFIG_ARTIFACTS
from .semantic import build_aws_lza_semantic_model
from .utils import (
    _INFRASTRUCTURE_OU,
    _LZA_CONTRACT,
    _WORKLOADS_OU,
    _aws_lza_intent,
    _central_network_services_config,
    _core_vpc_config,
    _guardduty_config,
    _identity_center_config,
    _management_access_role,
    _mandatory_accounts,
    _sample_recommendation_runbook_lines,
    _security_hub_config,
    _tgw_route_tables,
    _workload_accounts,
    _write_yaml,
)

_TARGET_CAPABILITY_HEADER = (
    "# yaml-language-server: $schema=none\n"
    "# Generated by intent-engine — intent artifact, not deployable configuration.\n"
)


def gen_lza_target_capability_graph(intent: Any, output_dir: Path) -> None:
    report = getattr(intent, "target_capability_report", None)
    if not report:
        return
    write_yaml_artifact(
        output_dir / "target-capability-graph.yaml",
        report,
        _TARGET_CAPABILITY_HEADER,
    )


def gen_lza_organization_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    data = {
        "enable": True,
        "organizationalUnits": [{"name": name} for name in intent.organizational_units],
        "serviceControlPolicies": [],
        "taggingPolicies": [],
        "backupPolicies": [],
    }
    _write_yaml(output_dir, "organization-config.yaml", data)


def gen_lza_accounts_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    _write_yaml(
        output_dir,
        "accounts-config.yaml",
        {
            "mandatoryAccounts": _mandatory_accounts(intent),
            "workloadAccounts": _workload_accounts(intent),
        },
    )


def gen_lza_global_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    data = {
        "homeRegion": intent.home_region,
        "enabledRegions": intent.enabled_regions,
        "managementAccountAccessRole": _management_access_role(intent),
        "terminationProtection": True,
        "cloudwatchLogRetentionInDays": 2555,
        "cdkOptions": {
            "centralizeBuckets": True,
            "useManagementAccessRole": True,
        },
        "controlTower": {"enable": str(intent.org_mode) == "control-tower"},
        "snsTopics": {
            "deploymentTargets": {"organizationalUnits": ["Root"]},
            "topics": [],
        },
        "tags": [],
        "logging": {
            "account": intent.log_archive_account,
            "centralizedLoggingRegion": intent.home_region,
            "cloudtrail": {
                "enable": intent.centralized_logging,
                "organizationTrail": intent.centralized_logging,
            },
            "sessionManager": {
                "sendToCloudWatchLogs": intent.centralized_logging,
                "sendToS3": intent.centralized_logging,
            },
            "centralLogBucket": {"lifecycleRules": []},
            "accessLogBucket": {"lifecycleRules": []},
        },
    }
    _write_yaml(output_dir, "global-config.yaml", data)


def gen_lza_security_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    data = {
        "homeRegion": intent.home_region,
        "accessAnalyzer": {"enable": True},
        "iamPasswordPolicy": {
            "allowUsersToChangePassword": True,
            "hardExpiry": False,
            "requireUppercaseCharacters": True,
            "requireLowercaseCharacters": True,
            "requireSymbols": True,
            "requireNumbers": True,
            "minimumPasswordLength": 14,
            "passwordReusePrevention": 24,
            "maxPasswordAge": 90,
        },
        "awsConfig": {"enableConfigurationRecorder": True},
        "cloudWatch": {
            "metricSets": [],
            "alarmSets": [],
        },
        "centralSecurityServices": {
            "delegatedAdminAccount": intent.audit_account,
            "ebsDefaultVolumeEncryption": {"enable": True, "excludeRegions": []},
            "s3PublicAccessBlock": {"enable": True, "excludeAccounts": []},
            "scpRevertChangesConfig": {"enable": True},
            "macie": {
                "enable": str(intent.compliance_overlay) != "none",
                "excludeRegions": [],
                "policyFindingsPublishingFrequency": "FIFTEEN_MINUTES",
                "publishSensitiveDataFindings": str(intent.compliance_overlay)
                in {"regulated", "financial-services", "healthcare"},
            },
            "guardduty": _guardduty_config(intent),
            "snsSubscriptions": [],
            "securityHub": _security_hub_config(intent),
            "ssmAutomation": {"excludeRegions": [], "documentSets": []},
        },
    }
    _write_yaml(output_dir, "security-config.yaml", data)


def gen_lza_iam_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    data = {
        "homeRegion": intent.home_region,
        "identityCenter": _identity_center_config(intent),
    }
    _write_yaml(output_dir, "iam-config.yaml", data)


def gen_lza_network_config(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    data = {
        "homeRegion": intent.home_region,
        "defaultVpc": {"delete": True, "excludeAccounts": []},
        "endpointPolicies": [],
        "transitGateways": [],
        "vpcs": [_core_vpc_config(intent)],
    }
    if intent.topology == "hub-spoke":
        data["centralNetworkServices"] = _central_network_services_config(intent)
        data["transitGateways"] = [
            {
                "name": "Core",
                "account": intent.network_account,
                "region": intent.home_region,
                "asn": 64512,
                "dnsSupport": "enable",
                "vpnEcmpSupport": "enable",
                "defaultRouteTableAssociation": "disable",
                "defaultRouteTablePropagation": "disable",
                "autoAcceptSharingAttachments": "enable",
                "routeTables": _tgw_route_tables(intent),
                "shareTargets": {"organizationalUnits": [_INFRASTRUCTURE_OU, _WORKLOADS_OU]},
                "tags": [],
            }
        ]
    _write_yaml(output_dir, "network-config.yaml", data)


def gen_lza_lineage_manifest(intent: Any, output_dir: Path) -> None:
    intent = _aws_lza_intent(intent)
    data = {
        "sourceContract": {
            "name": _LZA_CONTRACT.name,
            "kind": _LZA_CONTRACT.kind,
            "url": _LZA_CONTRACT.source_url,
            "baseline": str(intent.baseline),
            "mandatoryConfigFiles": AWS_LZA_CONFIG_ARTIFACTS,
        },
        "artifacts": [artifact.model_dump(by_alias=True) for artifact in _LZA_CONTRACT.artifacts],
        "lineage": [item.model_dump() for item in _LZA_CONTRACT.lineage],
    }
    _write_yaml(output_dir, "lineage-manifest.yaml", data)


def gen_lza_deployment_runbook(intent: Any, output_dir: Path) -> None:
    readiness = getattr(intent, "handoff_readiness", {})
    intent = _aws_lza_intent(intent)
    output_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AWS LZA Deployment Runbook",
        "",
        "## Inputs",
        "",
        f"- Baseline: `{intent.baseline}`",
        f"- Organization mode: `{intent.org_mode}`",
        f"- Home region: `{intent.home_region}`",
        f"- Enabled regions: `{', '.join(intent.enabled_regions)}`",
        "",
        "## LZA Config Contract",
        "",
        "Mandatory configuration files:",
        "",
        *[f"- `{name}`" for name in AWS_LZA_CONFIG_ARTIFACTS],
        "",
        "## Recommended Sample Configs",
        "",
        *_sample_recommendation_runbook_lines(intent),
        "## Sequence",
        "",
        (
            "1. Platform owner confirms AWS Organizations or Control Tower baseline "
            "matches `org_mode`."
        ),
        "2. Network owner reviews generated LZA network config against approved CIDR plan.",
        (
            "3. Security owner reviews logging, Security Hub, GuardDuty, and "
            "delegated admin decisions."
        ),
        (
            "4. Populate customer-specific Identity Center assignments and permission "
            "sets; identity owner approves delegated admin."
        ),
        "5. Release owner confirms account emails match the account vending process.",
        (
            "6. Platform owner populates customer-specific VPC route tables/subnets, "
            "TGW attachments, and optional security exports."
        ),
        "7. Manual gate: approve `decision-report.yaml`, `lineage-manifest.yaml`, and LZA diff.",
        "8. Run AWS LZA deployment using its documented installer and pipeline.",
        (
            "9. Preserve `decision-report.yaml`, `decision-audit.yaml`, and "
            "`lineage-manifest.yaml` as handoff evidence."
        ),
        (
            "10. Rollback note: revert through AWS LZA pipeline history; do not "
            "hand-edit generated artifacts."
        ),
        "",
        "## Manual Gates",
        "",
        "- Architecture owner approves unresolved decisions are zero.",
        "- Security owner approves logging/security services and IAM Identity Center scope.",
        "- Network owner approves CIDRs, TGW attachments, and routing boundaries.",
        "- Release owner confirms AWS LZA pipeline prereqs and rollback owner.",
        "",
        "## Dependencies",
        "",
        "- AWS Organizations or Control Tower baseline exists before LZA deploy.",
        "- Account vending/email ownership complete before accounts config handoff.",
        "- Identity Center delegated admin exists before IAM config deploy.",
        "- Network CIDR/IPAM plan approved before network config deploy.",
        "",
        "## Rollback",
        "",
        "- Stop AWS LZA pipeline before re-running with corrected config.",
        "- Revert to previous known-good LZA config commit.",
        "- Keep generated reports as evidence; regenerate after decision changes.",
        "",
        "## Boundary",
        "",
        "This handoff does not generate a parallel Terraform or Terragrunt landing-zone stack.",
        "Use AWS LZA for landing-zone deployment unless a documented gap requires custom IaC.",
    ]
    if readiness:
        handoff_allowed = readiness.get("handoffAllowed", False)
        lines.extend(
            [
                "",
                "## Handoff Readiness",
                "",
                f"- Status: `{readiness.get('status', 'unknown')}`",
                f"- Handoff allowed: `{handoff_allowed}`",
            ]
        )
    (output_dir / "deployment-runbook.md").write_text("\n".join(lines) + "\n")


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _contract_digest() -> str:
    rendered = json.dumps(_LZA_CONTRACT.model_dump(by_alias=True), sort_keys=True, default=str)
    return hashlib.sha256(rendered.encode("utf-8")).hexdigest()


def _plan_input_blockers(intent: Any) -> list[dict[str, Any]]:
    blockers = []
    account_names = {
        "Management",
        intent.log_archive_account,
        intent.audit_account,
        intent.security_tooling_account,
        *intent.workload_accounts,
    }
    if intent.topology == "hub-spoke":
        account_names.add(intent.network_account)
    email_names = {
        value.split("=", 1)[0].strip()
        for value in intent.account_emails
        if "=" in value and value.split("=", 1)[1].strip()
    }
    if not account_names.issubset(email_names):
        blockers.append(
            {
                "code": "AWS_LZA_PLAN_ACCOUNT_EMAILS_REQUIRED",
                "message": (
                    "Generated account emails use placeholder example.com addresses; replace "
                    "them with owned account vending emails before a no-interpretation LZA plan."
                ),
                "affectedArtifacts": ["accounts-config.yaml"],
                "owner": "release-owner",
            }
        )
    if not (
        intent.core_route_tables
        and intent.core_subnets
        and intent.core_nat_gateways
        and (intent.topology != "hub-spoke" or intent.tgw_attachments)
    ):
        blockers.append(
            {
                "code": "AWS_LZA_PLAN_NETWORK_DETAILS_REQUIRED",
                "message": (
                    "Generated network config still contains empty route tables, subnets, NAT "
                    "gateways, or TGW attachment details that require network-owner review "
                    "before plan."
                ),
                "affectedArtifacts": ["network-config.yaml"],
                "owner": "network-owner",
            }
        )
    if intent.topology == "hub-spoke" and not (
        intent.tgw_route_tables and intent.tgw_routes and intent.tgw_attachments
    ):
        blockers.append(
            {
                "code": "AWS_LZA_PLAN_TGW_ROUTES_REQUIRED",
                "message": (
                    "Hub-spoke topology has a transit gateway shell but no route entries "
                    "or attachment intent suitable for an interpretation-free plan."
                ),
                "affectedArtifacts": ["network-config.yaml"],
                "owner": "network-owner",
            }
        )
    return blockers


def _lza_plan_readiness(intent: Any) -> dict[str, Any]:
    blockers = _plan_input_blockers(intent)
    plan_allowed = not blockers
    return {
        "status": "ready" if plan_allowed else "blocked",
        "planAllowed": plan_allowed,
        "summary": (
            "All registered AWS LZA plan inputs are present."
            if plan_allowed
            else (
                "AWS LZA configuration is ready for review, but plan/diff still needs "
                "explicit inputs."
            )
        ),
        "blockers": blockers,
    }


def enrich_lza_handoff_readiness(intent: Any, readiness: dict[str, Any]) -> dict[str, Any]:
    lza_intent = _aws_lza_intent(intent)
    enriched = dict(readiness)
    enriched["planReady"] = _lza_plan_readiness(lza_intent)
    return enriched


def gen_lza_plan_manifest(payload: Any, output_dir: Path) -> None:
    readiness = getattr(payload, "handoff_readiness", {})
    intent = _aws_lza_intent(payload)
    immutable_inputs = [
        {
            "artifact": name,
            "sha256": _sha256_file(output_dir / name),
        }
        for name in AWS_LZA_CONFIG_ARTIFACTS
        if (output_dir / name).exists()
    ]
    plan_readiness = _lza_plan_readiness(intent)
    blockers = plan_readiness["blockers"]
    account_gate = (
        "Replace placeholder account emails with owned addresses."
        if any(blocker["code"] == "AWS_LZA_PLAN_ACCOUNT_EMAILS_REQUIRED" for blocker in blockers)
        else "Release owner confirms account emails are owned and ready for account vending."
    )
    data = {
        "target": {
            "name": "aws-lza",
            "type": "accelerator",
            "contract": _LZA_CONTRACT.name,
            "sourceUrl": _LZA_CONTRACT.source_url,
            "contractSha256": _contract_digest(),
        },
        "maturity": {
            "configReady": {
                "status": (readiness or {}).get("status", "unknown"),
                "allowed": bool((readiness or {}).get("handoffAllowed", False)),
                "summary": (readiness or {}).get("summary", ""),
            },
            "planReady": plan_readiness,
        },
        "immutableInputs": immutable_inputs,
        "sampleRecommendations": {
            "artifact": "sample-recommendations.yaml",
            "sha256": _sha256_file(output_dir / "sample-recommendations.yaml")
            if (output_dir / "sample-recommendations.yaml").exists()
            else "",
        },
        "prerequisites": [
            "AWS LZA repository and pipeline are owned by the downstream platform team.",
            "Generated configuration files are copied as an immutable bundle into that pipeline.",
            "Manual gates in handoff-plan.yaml and plan-manifest.yaml are approved.",
        ],
        "planInvocation": {
            "mode": "metadata-only",
            "approvedCommand": (
                "Run the owner-managed AWS LZA validation/diff command or pipeline against "
                "the immutableInputs listed in this manifest."
            ),
            "applyAllowed": False,
        },
        "expectedPlanOutputs": [
            "aws-lza-validation-result",
            "aws-lza-diff-or-plan-result",
            "owner approval record",
        ],
        "manualGates": [
            account_gate,
            "Network owner approves route tables, subnets, TGW attachments, and CIDR boundaries.",
            "Security owner approves IAM Identity Center and security service scope.",
            "Release owner confirms plan command/pipeline and rollback owner.",
        ],
        "blockers": plan_readiness["blockers"],
        "boundary": (
            "This manifest is plan metadata only. iac-llm-wrapper does not invoke AWS LZA, "
            "Terraform, cloud APIs, apply commands, or deployment pipelines."
        ),
    }
    _write_yaml(
        output_dir,
        "plan-manifest.yaml",
        {"schemaVersion": "intent-engine/plan-manifest/v1", **data},
    )


def gen_lza_decision_report(intent: Any, output_dir: Path) -> None:
    readiness = getattr(intent, "handoff_readiness", {})
    intent = _aws_lza_intent(intent)
    data = {
        "pattern": "aws-lza",
        "baseline": str(intent.baseline),
        "orgMode": str(intent.org_mode),
        "organizationName": intent.organization_name,
        "homeRegion": intent.home_region,
        "enabledRegions": intent.enabled_regions,
        "organizationalUnits": intent.organizational_units,
        "accounts": {
            "audit": intent.audit_account,
            "logArchive": intent.log_archive_account,
            "securityTooling": intent.security_tooling_account,
            "network": intent.network_account,
            "workloads": intent.workload_accounts,
        },
        "identity": {
            "identityCenterDelegatedAdmin": intent.identity_center_delegated_admin_account,
            "identityCenterPermissionSets": intent.identity_center_permission_sets,
            "identityCenterAssignments": intent.identity_center_assignments,
        },
        "network": {
            "topology": str(intent.topology),
            "cidr": intent.network_cidr,
        },
        "security": {
            "centralizedLogging": intent.centralized_logging,
            "securityHubEnabled": intent.security_hub_enabled,
            "guardDutyEnabled": intent.guardduty_enabled,
            "complianceOverlay": str(intent.compliance_overlay),
        },
        "semanticModel": build_aws_lza_semantic_model(intent).to_dict(),
    }
    if readiness:
        data["handoffReadiness"] = enrich_lza_handoff_readiness(intent, readiness)
    _write_yaml(output_dir, "decision-report.yaml", data)
