"""AWS LZA handoff helpers."""

from __future__ import annotations

from io import StringIO
from pathlib import Path
from typing import Any

import ruamel.yaml

from intent_engine.core.sample_config import GLOBAL_SAMPLE_REGISTRY, SampleConfig

from .contracts import AWS_LZA_SAMPLE_CONFIG_CONTRACT
from .models import AwsLzaIntent

_LZA_CONTRACT = AWS_LZA_SAMPLE_CONFIG_CONTRACT
_SECURITY_OU = "Security"
_INFRASTRUCTURE_OU = "Infrastructure"
_WORKLOADS_OU = "Workloads"
_MANAGEMENT_ACCOUNT = "Management"
_PLACEHOLDER_EMAIL_DOMAIN = "example.com"


def _yaml_dump(data: Any) -> str:
    yaml = ruamel.yaml.YAML()
    yaml.default_flow_style = False
    yaml.indent(mapping=2, sequence=4, offset=2)
    buf = StringIO()
    yaml.dump(data, buf)
    return "\n".join(line.rstrip() for line in buf.getvalue().splitlines()) + "\n"


def _write_yaml(output_dir: Path, name: str, data: Any) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    header = (
        "# yaml-language-server: $schema=none\n"
        "# Generated by intent-engine — AWS LZA handoff artifact.\n"
    )
    (output_dir / name).write_text(header + _yaml_dump(data))


def _aws_lza_intent(payload: Any) -> AwsLzaIntent | None:
    intent = getattr(payload, "intent", payload)
    if isinstance(intent, AwsLzaIntent):
        return intent
    return None


def _normalized_ous(intent: AwsLzaIntent) -> set[str]:
    return {ou.strip().lower() for ou in intent.organizational_units if ou.strip()}


def _management_access_role(intent: AwsLzaIntent) -> str:
    if str(intent.org_mode) == "control-tower":
        return "AWSControlTowerExecution"
    return "OrganizationAccountAccessRole"


def _slug(value: str) -> str:
    return "".join(char.lower() for char in value if char.isalnum()) or "account"


def _placeholder_email(account_name: str) -> str:
    return f"{_slug(account_name)}@{_PLACEHOLDER_EMAIL_DOMAIN}"


def _account_record(name: str, organizational_unit: str | None = None) -> dict[str, str]:
    account = {"name": name, "email": _placeholder_email(name)}
    if organizational_unit:
        account["organizationalUnit"] = organizational_unit
    return account


def _primary_vpc_account(intent: AwsLzaIntent) -> str:
    if intent.topology == "hub-spoke":
        return intent.network_account
    if intent.workload_accounts:
        return intent.workload_accounts[0]
    return intent.security_tooling_account


def _mandatory_accounts(intent: AwsLzaIntent) -> list[dict[str, str]]:
    return [
        _account_record(_MANAGEMENT_ACCOUNT),
        _account_record(intent.log_archive_account, _SECURITY_OU),
        _account_record(intent.audit_account, _SECURITY_OU),
    ]


def _workload_accounts(intent: AwsLzaIntent) -> list[dict[str, str]]:
    explicit_account_ous = {
        account.name: account.ou
        for account in intent.accounts
        if account.name.strip() and account.ou.strip()
    }
    accounts = [_account_record(intent.security_tooling_account, _SECURITY_OU)]
    if intent.topology == "hub-spoke":
        accounts.append(_account_record(intent.network_account, _INFRASTRUCTURE_OU))
    accounts.extend(
        _account_record(name, explicit_account_ous.get(name, _WORKLOADS_OU))
        for name in intent.workload_accounts
    )
    return accounts


def _security_hub_standards(intent: AwsLzaIntent) -> list[dict[str, Any]]:
    standards = [
        {
            "name": "AWS Foundational Security Best Practices v1.0.0",
            "enable": True,
            "deploymentTargets": {"organizationalUnits": ["Root"]},
            "controlsToDisable": [],
        }
    ]
    overlay = str(intent.compliance_overlay)
    if overlay == "regulated":
        standards.append(
            {
                "name": "NIST Special Publication 800-53 Revision 5",
                "enable": True,
                "deploymentTargets": {"organizationalUnits": ["Root"]},
                "controlsToDisable": [],
            }
        )
    elif overlay == "financial-services":
        standards.append(
            {
                "name": "PCI DSS v4.0.1",
                "enable": True,
                "deploymentTargets": {"organizationalUnits": ["Root"]},
                "controlsToDisable": [],
            }
        )
    elif overlay == "healthcare":
        standards.append(
            {
                "name": "NIST Special Publication 800-53 Revision 5",
                "enable": True,
                "deploymentTargets": {"organizationalUnits": ["Root"]},
                "controlsToDisable": [],
            }
        )
    return standards


def _identity_center_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "name": f"{intent.organization_name} Identity Center",
        "delegatedAdminAccount": intent.identity_center_delegated_admin_account,
        "identityCenterPermissionSets": [
            {
                "name": name,
                "description": f"{name} access boundary",
                "sessionDuration": "PT8H",
                "managedPolicies": [],
            }
            for name in intent.identity_center_permission_sets
        ],
        "identityCenterAssignments": [
            _identity_center_assignment(assignment)
            for assignment in intent.identity_center_assignments
        ],
    }


def _identity_center_assignment(value: str) -> dict[str, Any]:
    parts = [part.strip() for part in value.split(":") if part.strip()]
    principal = parts[0] if parts else value
    permission_set = parts[1] if len(parts) > 1 else ""
    target = parts[2] if len(parts) > 2 else ""
    return {
        "name": value,
        "principalType": "GROUP",
        "principalId": principal,
        "permissionSetName": permission_set,
        "deploymentTargets": {"accounts": [target] if target else []},
    }


def _guardduty_export_configuration(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "enable": intent.centralized_logging,
        "overrideExisting": True,
        "destinationType": "S3",
        "exportFrequency": "FIFTEEN_MINUTES",
    }


def _guardduty_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "enable": intent.guardduty_enabled,
        "autoEnableOrgMembers": True,
        "excludeRegions": [],
        "s3Protection": {"enable": intent.centralized_logging, "excludeRegions": []},
        "eksProtection": {"enable": True, "excludeRegions": []},
        "exportConfiguration": _guardduty_export_configuration(intent),
        "lifecycleRules": [],
    }


def _security_hub_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "enable": intent.security_hub_enabled,
        "autoEnableOrgMembers": True,
        "regionAggregation": True,
        "snsTopicName": "Security",
        "notificationLevel": "HIGH",
        "excludeRegions": [],
        "standards": _security_hub_standards(intent),
    }


def _sample_recommendation_runbook_lines(intent: AwsLzaIntent) -> list[str]:
    decisions = SampleConfig.to_builtin(intent.model_dump())
    matches = GLOBAL_SAMPLE_REGISTRY.find_best_matches(
        decisions,
        pattern="aws-lza",
        limit=3,
    )
    if not matches:
        return ["No registered sample recommendations found.", ""]

    lines = ["Ranked recommendations are also persisted in `sample-recommendations.yaml`.", ""]
    for match in matches:
        lines.append(
            f"- `{match.sample.name}`: {match.same_count}/"
            f"{match.total_sample_decisions} decisions match, "
            f"{match.different_count} differ, fixture `{match.sample.fixture_name}/`"
        )
    return lines + [""]


def _core_vpc_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "name": "Core",
        "account": _primary_vpc_account(intent),
        "region": intent.home_region,
        "cidrs": [intent.network_cidr],
        "enableDnsHostnames": True,
        "enableDnsSupport": True,
        "instanceTenancy": "default",
        "routeTables": [],
        "subnets": [],
        "natGateways": [],
        "transitGatewayAttachments": [],
        "tags": [],
    }


def _central_network_services_config(intent: AwsLzaIntent) -> dict[str, Any]:
    return {
        "delegatedAdminAccount": intent.network_account,
        "gatewayLoadBalancers": [],
        "ipams": [],
        "networkFirewall": {
            "firewalls": [],
            "policies": [],
            "rules": [],
        },
        "route53Resolver": {
            "endpoints": [],
            "firewallRuleGroups": [],
        },
    }
